### ISSUE TITLE
Unclear to new users that set "Active tab" must always be added to workflow

### ISSUE THREAD

**Issue by WybeBosch** [Kholid060/automa#10]
**Describe the bug**
Workflow wont work without setting active tab

**To Reproduce**
I created a workflow to happen on the current page im on with a simple "click" block. 
The click block did produce an error in your build in logger frame but it just said "error"
I inspected the extensions background page and saw this error 
![image](https://user-images.githubusercontent.com/40889930/140301499-032a3b89-eeb3-420d-9909-668c992a3f4a.png)

Causing me to think hm, iguess i need to set the page as "Active page" first.

**Expected behavior**
The error in your framework should say a bit more than "error" (If possible)
But perhaps a warning or popup that the user forgot to set "active" tab would also work.

**Screenshots**

**Desktop (please complete the following information):**
MacOs
Chrome - Version 94.0.4606.81 (Official Build) (x86_64)

**Comment by Kholid060** [comment]
> I created a workflow to happen on the current page I'm on with a simple "click" block.
The click block did produce an error in your build in logger frame but it just said "error"
I inspected the extensions background page and saw this error
image
Causing me to think hm, I guess I need to set the page as "Active page" first.

Like the error said, you need to add the "active tab" or "new tab" block before using any from the web interaction category.

> The error in your framework should say a bit more than "error" (If possible)
But perhaps a warning or popup that the user forgot to set the "active" tab would also work.

You can check the log of the workflow that you're running to see what the error is. I think I need to make it more clear so the user doesn't confuse what the error is in their workflow and will fix this in the next version
![image](https://user-images.githubusercontent.com/22908993/140427775-ed62e24c-1346-4086-bd5d-2de1f366ec32.png)

**Comment by WybeBosch** [comment]
Oh how strange, for me it just said that the "click function" had an error. (With a little label "Error") But it did not display the actual cause beneath it. 

Now that i try to reproduce that action, i do actually see the error beneath it. So either it was a weird fluke, or it was something you fixed in the update of the extension yesterday ! :)

**Comment by Kholid060** [comment]
Yes, I've fixed it yesterday
