### ISSUE TITLE
can't click element 

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#100]
**Describe the bug**

**To Reproduce**

1 target url :  https://app.modaiyun.com/share-token/1460796667327770624?source=preview
2  I get comment icon selector but no effect

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Kholid060** [comment]
Are you sure you got the right element? Because it working for me with `[data-hint="Comments"] .svg_icon.icon_comment_v2` as the selector in the click element block

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/142188755-51905daa-162a-4304-9e5b-8d686d4404ed.png)

**Comment by whwh656** [comment]
> Are you sure you got the right element? Because it working for me with `[data-hint="Comments"] .svg_icon.icon_comment_v2` as the selector in the click element block

As the way `[data-hint="Comments"] .svg_icon.icon_comment_v2` ,  **I try it but no effect**

**Comment by whwh656** [comment]
finished
