### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by bolei-zhang** [Kholid060/automa#101]
**Describe the bug**
After crawling webpages after about 10k times, my Chrome crashes with the error "Out of memory". The worse is I could no longer use the current version of Chrome. Every time I started the browser, it quits automatically after a few secons.

**To Reproduce**
1. Start automa
2. Craw and download the page content for about 10k times with loop

**Desktop (please complete the following information):**
 - Chrome 96.0.4664

**Comment by Kholid060** [comment]
I haven't tested the extension with a large amount of data and tried to disable the extension to prevent the browser from crashing.
