### ISSUE TITLE
Webhook error while looping data

### ISSUE THREAD

**Issue by tellodaniel** [Kholid060/automa#105]
**Describe the bug**
I have data stored and I'm iterating with loop data block. In every iteration I'm sending the data to a webhook using this content body:

```
{
  "category": {{ loopData@ycmJdp.category }},
  "name": {{ loopData@ycmJdp.name }},
  "description": {{ loopData@ycmJdp.description }},
  "price": {{ loopData@ycmJdp.price }},
  "discount_price": {{ loopData@ycmJdp.discount_price }},
  "sku": {{ loopData@ycmJdp.sku }},
  "images_urls": {{ loopData@ycmJdp.images_urls }},
  "colors": {{ loopData@ycmJdp.colors }},
  "external_url": {{ loopData@ycmJdp.external_url }}
}
```

I'm getting the following error:
Unexpected token { in JSON at position 17

**Comment by tellodaniel** [comment]
Found out that has something to do with spaces and double quotes. Now the problem is that is not builing the json body correctly. If I add double quotes it will not insert the value and if I remove it will not add the string quotes.


```
 Parameters: 
"category"=>" {{loopData@ycmJdp.category}} ", 
"name"=>"{{loopData@ycmJdp.name}}", 
"description"=>"{{loopData@ycmJdp.description}}",
"price"=>"{{loopData@ycmJdp.price}}",
"discount_price"=>"{{loopData@ycmJdp.discount_price}}",
"sku"=>"{{loopData@ycmJdp.sku}}", 
"external_url"=>"https://"
```

**Comment by tellodaniel** [comment]
Found out that it can be solved by using the following body: 

```
{
 "importer": {{loopData@DQOLcx}}
}
```

Could be useful to know in the documentation that full data can be acessed like that.

**Comment by Kholid060** [comment]
Noted, if the full data is an object you actually can write just `{{loopData@DQOLcx}}` inside the body like the image below
![image](https://user-images.githubusercontent.com/22908993/142339768-5bc482d4-5188-401f-86d7-b4e5c6a838e3.png)
