### ISSUE TITLE
Multiple uses on one block

### ISSUE THREAD

**Issue by Chokeey** [Kholid060/automa#106]
Hello,
Would it be possible for you to add multiple uses for a block, for example, my workflow looks like this.

**Trigger > Loop > New Tab > Click Element > Loop breakpoint.**

As the workflow repeats its self I want another task to also be running simultaneously. For example, when the workflow reaches **_Click Element_** it would close the page after 5 seconds, whilst still looping itself. So the workflow wouldn't wait for the page to close to open a new one. It would still run as normal.

It would look something like this, (you could draw multiple lines from block to block)
![image](https://user-images.githubusercontent.com/90982478/142275142-330457c5-1688-4d79-a0b2-45293d43f062.png)

**Comment by Kholid060** [comment]
It's not possible to run tasks simultaneously because when the workflow reaches the block that doesn't have an output connection, the workflow will automatically stop.

> when the workflow reaches Click Element it would close the page after 5 seconds, whilst still looping itself.

You can reuse the tab instead of closing it by checking the "Update previously opened tab" in the **new tab** block

**Comment by Kholid060** [comment]
And you don't need to connect the **loop breakpoint** block with the **loop data** block
