### ISSUE TITLE
Make the connection lines smoother

### ISSUE THREAD

**Issue by dyxang** [Kholid060/automa#108]
**Is your feature request related to a problem? Please describe.**
If a workflow is too long and then I want to place it in rows to make it more readable, the connecting curves between blocks can become distracting in the background.

**Describe the solution you'd like**
Use smoother lines to connect the blocks. Use straight lines to connect the blocks.

**Describe alternatives you've considered**
Make it possible for the right side of a block to be connected first. Or add nodes above and below the blocks.

**Additional context**
Original look
![image](https://user-images.githubusercontent.com/36600710/142381156-ccf692d8-83b7-4f48-a2b9-7d27e0fe700e.png)
![image](https://user-images.githubusercontent.com/36600710/142381209-cafa0406-3728-4877-a71c-42fd7325271a.png)

Desired look
![无标题](https://user-images.githubusercontent.com/36600710/142381267-e07cbbe3-f443-45f5-b42c-ca886562bda5.jpg)

**Comment by Kholid060** [comment]
You can double-click the line to reroute it

**Comment by dyxang** [comment]
> You can double-click the line to reroute it ![image](https://user-images.githubusercontent.com/22908993/142403845-f0276ff8-49ec-49e6-b3f0-46433dd28aa5.png)

Thank you.but I tried like this then the result was:
![image](https://user-images.githubusercontent.com/36600710/142421846-86f7a91c-0411-429c-bd06-809abc1f94ba.png)
after that,I tried double-clicking to restore it, but it didn't work.

- Automa: 0.4.7
- Windows 10
- Edge 95.0.1020.40

**Comment by Kholid060** [comment]
Update the extension to the latest version v0.5.1
