### ISSUE TITLE
how to get text  on table？

### ISSUE THREAD

**Issue by allen-studio** [Kholid060/automa#109]
The table element selector like  li:nth-child(1) > .xkzh、li:nth-child(2) > .xkzh、li:nth-child(3) > .xkzh、li:nth-child(4) > .xkzh.
how can i get this text on one get text flow?thx

**Comment by Kholid060** [comment]
Try checking the "multiple" checkbox and use the `li .xkzh` selector

**Comment by allen-studio** [comment]
> Try checking the "multiple" checkbox and use the `li .xkzh` selector

Thx,it works
