### ISSUE TITLE
js块与非js块之间的参数是否支持互相传递

### ISSUE THREAD

**Issue by xiaoxuetong** [Kholid060/automa#111]
How to get parameters in the next block using automaNextBlock, how to get parameters in the next block if the next block is JS block, how to pass some parameters in js block to the next non-JS block, please ask, if there is an example, it would be better.  Thank you very much!  
If I want to open [New Tab block] in the address contains dynamic parameters, how to set?  Is it possible to preload a JS block to set dynamic parameters?  

使用automaNextBlock传递的参数，在下一个块中怎么获取，如果下一个块是js块怎么得到传递的参数，在js块中如何将一些参数传递到下一个非js块中，请教一下，如果有例子就更好了。谢谢！
请问如果我要在【New Tab块】中打开的地址中包含动态参数，该如何去设置？可以前置一个js块去设置好动态参数吗？

**Comment by Kholid060** [comment]
You can't access dynamic data inside a javascript block.

> If I want to open [New Tab block] in the address contains dynamic parameters, how to set it?

In the **New tab** block URL input, if you want to use dynamic parameter you can write `https://google.com/search?q={{dataColumns@0.path}}`. You can read more [in here](https://github.com/Kholid060/automa/wiki/Features#reference-data)

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/142588957-c1b2e71a-f4cd-430a-9119-5e4caf72dfc8.png)

![image](https://user-images.githubusercontent.com/20383505/142588886-f42df929-c7e4-4bb4-844f-0bc94a578ef0.png)

![image](https://user-images.githubusercontent.com/20383505/142589026-6a379ea0-2ed0-45e6-9da2-fff70e7eebd4.png)



> You can't access dynamic data inside a javascript block.
> 
> > If I want to open [New Tab block] in the address contains dynamic parameters, how to set it?
> 
> In the **New tab** block URL input, if you want to use dynamic parameter you can write `https://google.com/search?q={{dataColumns@0.path}}`. You can read more [in here](https://github.com/Kholid060/automa/wiki/Features#reference-data)

**Comment by Kholid060** [comment]
You can use this as an example, replace the extension from `txt` to `json` and import it by clicking the "Import workflow" button on the workflows page
[data columns.txt](https://github.com/Kholid060/automa/files/7569541/data.columns.txt)

**Comment by xiaoxuetong** [comment]
Thank you for your answer.  Another question is, how can parameters passed by [ automaNextBlock ] be retrieved in the next block? Does the next block have to be a non-JS block? I tried without success.

**Comment by Kholid060** [comment]
> how can parameters passed by [ automaNextBlock ] be retrieved in the next block?

You can write `{{prevBlockData}}` if you want to access the js block parameter in the next block of js block. 

> Does the next block have to be a non-JS block?

No, it doesn't have to.

**Comment by xiaoxuetong** [comment]
OK, thank you.

**Comment by whwh656** [comment]
> have

![image](https://user-images.githubusercontent.com/20383505/143766009-671fd94d-5318-40cc-9b07-afadf512c8c3.png)
![image](https://user-images.githubusercontent.com/20383505/143766022-e686d98f-9bac-46ce-85fe-1be8af6a033c.png)
![image](https://user-images.githubusercontent.com/20383505/143766030-28782420-2d82-44e7-b02d-73365211b5e7.png)
As the  first picture's tips, why we run javascirptcode : automaNextBlock([{"a":123}])   rather than automaNextBlock({"a":123})
