### ISSUE TITLE
How to remove a connection?

### ISSUE THREAD

**Issue by vadi2** [Kholid060/automa#113]
I'd like to rewire a connection to go elsewhere, but I don't see how to do it. Just dragging it elsewhere doesn't seem to change it.

**Comment by Kholid060** [comment]
Click the line and then press delete or right-click the line and click the X button
![Animation](https://user-images.githubusercontent.com/22908993/142607040-bb89b5c7-8995-4fbd-90c5-4a052f88040b.gif)

**Comment by vadi2** [comment]
Ah thanks. I use a Chromebook so there's only a Backspace key and no Delete - would be great if it was also supported.
