### ISSUE TITLE
Can you add an external input parameter interface to the form block?

### ISSUE THREAD

**Issue by Masterlovsky** [Kholid060/automa#118]
Like the following usage scenario,  I want to search google with the keyword "stackflows" but I don't want to click into automa and click the form button and  change the words. Is there a way to quickly pass external input into the form block?

**Comment by Kholid060** [comment]
There's no other way to change the parameter without clicking into automa, but I guess you can use **Global data** for the fastest way to change the form parameter. You only need to insert the keyword you want by clicking the **Global data** button first, and then in the forms input `{{globalData}}`.
![image](https://user-images.githubusercontent.com/22908993/142756421-d8692979-c569-430f-8e7f-025d1d9c3f65.png)

**Comment by Masterlovsky** [comment]
Yes, that's a good idea! Thanks~ @Kholid060 
But when I try to use global data with a json format, I can't get the value of the key... did I write something wrong?
![image](https://user-images.githubusercontent.com/45965357/142761000-9e5b5790-c706-4292-a73e-3fd0403d4651.png)
![image](https://user-images.githubusercontent.com/45965357/142761018-7cea9a86-d53a-4da7-ae6c-ac2afef08782.png)

**Comment by Kholid060** [comment]
You need to add `@` before writing the key, for example, `globalData@key`

**Comment by Masterlovsky** [comment]
> You need to add `@` before writing the key, for example, `globalData@key`

And if I add this "@", the whole plain letter will be fill into the blank.
![image](https://user-images.githubusercontent.com/45965357/142761887-09179c3c-f7fd-41bc-aec0-eb4a18a7748b.png)
![image](https://user-images.githubusercontent.com/45965357/142761892-8b84fc56-4636-4afc-8c45-04566310ec50.png)

**Comment by Kholid060** [comment]
How do you write the data inside the **Global data**? Is it an object?
If you want an example you can use the file below, replace it from `.txt` to `.json` and then import it

[SciHub.txt](https://github.com/Kholid060/automa/files/7576295/SciHub.txt)
