### ISSUE TITLE
New tab block doesn't save IP addresses

### ISSUE THREAD

**Issue by teleksterling** [Kholid060/automa#12]
**Describe the bug**
New tab block doesn't correctly handle IP addresses as URLs, including not replacing previous value in workflow save, and exported workflow json file.

I also found in one exported workflow that when I entered 'http://192.168.x.xx:1234' that the saved value was 'http://192.168.x.xx:1234.com', but I haven't been able to replicate this behaviour.

**To Reproduce**
1. Create new workflow with trigger and new tab block
2. Set new tab URL to 'http://204.68.111.105/'  (sourceforge.net IP address)
3. Click save
4. Click '...' menu and export workflow
5. Review file and see newtab URL isn't set
6. Return to workflow tab
7. Click play button
8. New tab opens, but onmibar contains Automa address, and 'Your file couldn't be accessed' error.
9. Return to workflow tab
10. Change new tab block URL to 'http://google.com'
10. Click play button
11. New tab loads correctly with google.com.
12. Return to workflow tab
13. Change new tab block URL to 'http://192.168.0.1' (or other IP address)
14. Click save and export
15. Click play
16. See new tab load with previously entered URL (here it's google.com), and this is reflected in the exported json.

**Expected behavior**
1. Save file and exported workflow should reflect entered URL, even if it's an IP address.
2. If invalid data is entered that is not saved, UI should alert user that the save was unsuccessful.
3. When the 'Please enter a URL' alert that is displayed disappears on mouse click or other action, but the input field still contains invalid data, another visual indication should persist (e.g. changing text box shading to red) 

**Desktop (please complete the following information):**
 - Chrome Version 95.0.4638.69 (Official Build) (32-bit)
 - Edition	Windows 10 Enterprise
 - Version	21H1
 - OS build	19043.1237
 - Experience	Windows Feature Experience Pack 120.2212.3530.0

**Additional context**

- I've verified that if I change the exported file and import it to a new workflow that the workflow runs as expected.
- I also noticed that the blue 'unsaved changes' dot doesn't appear on the Save button when the changing the URL from a domain name to an IP address.
- I also don't know if it's intentional, but URLs not prefixed by a protocol

**Comment by Kholid060** [comment]
The regex validation doesn't accept IP as a valid URL, will fix this in the next version
