### ISSUE TITLE
add ability to toggle(enable or disable) the task in extension dropdown menu

### ISSUE THREAD

**Issue by msongz** [Kholid060/automa#121]
![image](https://user-images.githubusercontent.com/2059694/142760099-a433c07b-196a-4eea-9791-73caadd16bf4.png)

User may want to disable the task and enable it later

**Comment by Kholid060** [comment]
> User may want to disable the task and enable it later

Can you elaborate more on this?
I mean, if the user doesn't want to use the workflow, they can simply ignore it.

**Comment by msongz** [comment]
@Kholid060 sure, like a trigger is interval, so the task will run again and again, but at sometimes user just want to turn it off quickly

**Comment by Kholid060** [comment]
Got it, that's actually a good idea and I think this is also will resolve #70
