### ISSUE TITLE
Call a flow from within another

### ISSUE THREAD

**Issue by gbishop** [Kholid060/automa#125]
**Is your feature request related to a problem? Please describe.**
I see I can call multiple flows from Collections but I want to trigger a sequence of flows at a specific time. 

**Describe the solution you'd like**
What I'd like is the ability to trigger a flow at a time, then have it trigger another flow, which could then trigger another. This would make reusing flows easy like subroutines. 

**Describe alternatives you've considered**
Collections are almost what I need but I don't see how to control when they trigger.

**Additional context**
Very neat extension!

**Comment by whwh656** [comment]
good idea @gbishop

**Comment by Kholid060** [comment]
If a workflow can trigger another workflow, I think it would make the collection feature kinda pointless. And I need to refactor the code that executes workflow because there's a [circular dependency](https://en.wikipedia.org/wiki/Circular_dependency) when trying to trigger another workflow. But I'll consider adding this feature

**Comment by gbishop** [comment]
Yes. Recursion and arbitrary looping would come along as side effects. 

I just built a pair of flows. One blocks a phone number in the evening and another unblocks it in the morning. The flows begin with the same long sequence to login. Splitting login out into its own flow would have been great.

**Comment by gkTim** [comment]
This would be a really great feature!

We also have a lot of steps we need to do every time.

Maybe a quick win for such a case would be a duplicate button for flows?
Of cause if you have a change you need to do it in every flow, but for the initial setup it would help.

**Comment by gkTim** [comment]
@Kholid060 Thx for this fast implementation!
Really nice extension!
