### ISSUE TITLE
Can the js block support page-independent execution

### ISSUE THREAD

**Issue by xiaoxuetong** [Kholid060/automa#128]
**Is your feature request related to a problem? Please describe.**
I want to initialize some of the parameters I need through the js block, but now I have to have a new TAB block open, open a meaningless url, if I execute the JS block and then open the desired url, it will be a long time in between.  Can javascript block support page-independent execution, that is, can execute js block in any case, may not open the page, or is unconscious.  

我想通过js块先网络请求初始化一些我需要的参数，但现在的做法是，必须先有打开的 new tab 块，打开一个无意义的网址，如果执行js块后再打开想要的网址，这中间会等待好长的一段时间。请问js块能不能支持不依赖页面执行，也就是任何情况下都可以执行js块，可能还没打开页面的时候，或者是无感知的。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/34703535/142972008-8adbb5ce-66db-4290-a71e-062fafd0118f.png)

**Comment by Kholid060** [comment]
The javascript block is meant to be executed on a website, and I don't think there's another way to execute the javascript code.

**Comment by xiaoxuetong** [comment]
If I just need new TAB to open a random web page, in order for the next JS block to execute properly. However, the new TAB will consume a lot of waiting time. How can I optimize it?

**Comment by Kholid060** [comment]
The new tab will move to the next block once the page is fully loaded. So, it depends on how fast the page is loaded.
