### ISSUE TITLE
This extension is not trusted by Enhanced Safe Browsing. 

### ISSUE THREAD

**Issue by reyesvicente** [Kholid060/automa#13]
**Describe the bug**

**To Reproduce**
- If you already have it, uninstall then re-install.
- After reinstalling, the pop-up would appear.

**Expected behavior**
No prompts should appear when installing the extension

**Screenshots**
![Screenshot 2021-11-05 at 10 32 00 PM](https://user-images.githubusercontent.com/45283313/140527802-b54069a4-b7be-4551-8f72-7fb77a3a0b9a.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 
 - Version 12.0.1

**Additional context**
N/A

**Comment by bxb100** [comment]
![image](https://user-images.githubusercontent.com/20685961/140563014-a723556f-a1dd-43b5-9d0a-3b5d415c3e11.png)

source : https://support.google.com/chrome_webstore/answer/2664769?hl=en-GB#zippy=%2Cinstall-with-enhanced-safe-browsing

**Comment by Kholid060** [comment]
I don't actually know why this happens, because I've followed and filled all the forms in the privacy practices tab in the chrome web store dashboard.

**Comment by reyesvicente** [comment]
> I don't actually know why this happens, because I've followed and filled all the forms in the privacy practices tab in the chrome web store dashboard.

I'm not sure too. I guess we just wait for the extension to mature, then.

**Comment by Kholid060** [comment]
It looks like the popup is no longer appear when installing the extension with Enhanced Safe Browsing is on
