### ISSUE TITLE
New "paste" from clipboard function

### ISSUE THREAD

**Issue by LucianCr** [Kholid060/automa#134]
Can you please add a paste from clipboard function ?

![image](https://user-images.githubusercontent.com/53472025/143477361-7f7078a0-f763-435a-a148-cdf020a2d34f.png)

from the above picture i can use "click element" block to click the "copy to clipboard" button and then paste the data into a data column

**Comment by Kholid060** [comment]
I think it will be more convenient to add a function to get the value of the input instead of paste from the clipboard because it requires permission to read and write content to the clipboard
