### ISSUE TITLE
How i can past some saved scraped data

### ISSUE THREAD

**Issue by Martin-Hausleitner** [Kholid060/automa#136]
how can i past here some scraped data like varibles
![image](https://user-images.githubusercontent.com/55828102/143722400-8136ff1a-c584-4238-b698-9824d593a6a1.png)

**Comment by Kholid060** [comment]
You put scraped data by writing `{{ dataColumsn@path }}`, you learn more about it on the [reference data](https://github.com/Kholid060/automa/wiki/Features#data-columns) docs.
