### ISSUE TITLE
keydown of trigger event 

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#137]
**Describe the bug**
press keycode Enter no effect
![image](https://user-images.githubusercontent.com/20383505/143830980-7c1fa62e-badf-4d12-80a7-c19fb030f91f.png)
[sitcomment.txt](https://github.com/Kholid060/automa/files/7616583/sitcomment.txt)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Add any other context ab
[sitcomment.txt](https://github.com/Kholid060/automa/files/7616586/sitcomment.txt)
out the problem here.

**Comment by Kholid060** [comment]
Try change the `keydown` event with `submit` and change the selector to `#form`

**Comment by whwh656** [comment]
great !
