### ISSUE TITLE
I want to load the JS file in the loaded page.  But there are limitations  

### ISSUE THREAD

**Issue by xiaoxuetong** [Kholid060/automa#138]
**Is your feature request related to a problem? Please describe.**
I want to load the JS file in the loaded page.  But there are limitations  
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/34703535/143835717-090f3c8e-6fb1-4772-8e80-d955c2af8105.png)

![image](https://user-images.githubusercontent.com/34703535/143835959-19e332ed-1105-48a4-8241-f038e9e521ed.png)

**Describe alternatives you've considered**
Hope to add [js file needed for initial pre-loading of the page to the block]
It is desirable to add a block where the page initialization preloads the required JS files to the page for loading additional JS files, or CSS files.  
Or support directly after loading the page can be tampered with

**Additional context**

**Comment by Kholid060** [comment]
try
```js
const script = document.createElement('script')
script.src = 'https://html2canvas.hertzen.com/dist/html2canvas.min.js'
script.type = 'text/javascript'

script.onload = () => {
  console.log(html2canvas)
}

document.head.appendChild(script)
```

**Comment by Kholid060** [comment]
And I don't think it's necessary to add block just for preload JS or CSS file when you can preload it using the js block

**Comment by xiaoxuetong** [comment]
because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'"
CSP will prevent the page from loading, I tried to put the contents of js file into JS block execution, but there is a string length limit  
It would be nice if you could tamper with the page

Encountered this KIND of CSP, it is recommended to load the JS file, directly obtain the content, and then render on the pag
