### ISSUE TITLE
无法定位元素

### ISSUE THREAD

**Issue by Fhaohaizi** [Kholid060/automa#14]
2021年11月06日，刚刚才Chrome Web store下载的。Chrome版本 95.0.4638.69
使用插件自带的定位功能，无法捕获当前页面的元素selector。

经过我测试发现，当我打开两个Chrome的时候，第二个Chrome往往不能成功。第一个Chrome可以。

**Comment by Kholid060** [comment]
Can you share which website you're in when you try to use the element selector feature?

**Comment by bxb100** [comment]
@Kholid060 this video show this bug

https://user-images.githubusercontent.com/20685961/140605680-07e13b5e-a4ea-4541-9500-17899a346b89.mov

**Comment by Kholid060** [comment]
@bxb100 thanks for the video. I never tested this extension with multiple windows, but I've fixed this bug and it'll be out in the next update.

**Comment by Fhaohaizi** [comment]
I just tried it and it worked magically.

thanks

From Google Translate.
