### ISSUE TITLE
hover element

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#145]
**Is your feature request related to a problem? Please describe.**

Can Automa support  hover to element ?  
@Kholid060

**Comment by Kholid060** [comment]
Can you explain the use case of this?

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/144224731-35fd2199-53db-474e-a62b-67026203b849.png)
![image](https://user-images.githubusercontent.com/20383505/144225019-a9ecdf88-8e90-4efe-9693-c781801adfb7.png)

**Comment by Kholid060** [comment]
It looks like it using [`mouseenter`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event)/[`mouseover`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseover_event) which is currently doesn't available in the trigger event block. I will add it in the next update

**Comment by whwh656** [comment]
Thanks !

**Comment by whwh656** [comment]
Another question  for help,  I have send one email to your gmail 
Look forward to your reply
![image](https://user-images.githubusercontent.com/20383505/144230233-29118107-b32c-4b37-a0a8-69ae6b517ea7.png)

**Comment by Kholid060** [comment]
I don't know why but your email ends up in the spam folder in Gmail

**Comment by whwh656** [comment]
done!   add delay block
