### ISSUE TITLE
It is hoped that CSP restrictions can be bypassed when loading JS files or network requests  

### ISSUE THREAD

**Issue by xiaoxuetong** [Kholid060/automa#149]
**Is your feature request related to a problem? Please describe.**
It is hoped that CSP restrictions can be bypassed when loading JS files or network requests  

Test the address: https://shuilian.guangdong.chinatax.gov.cn/slkppt/login  
![image](https://user-images.githubusercontent.com/34703535/144349883-2e12af30-afdc-4c87-bf24-43c67379790d.png)

**Describe the solution you'd like**
Load resources on cSP-restricted pages, and network requests can be used on CSP-restricted pages.  

**Describe alternatives you've considered**
Can open a virtual page that is hidden and has no CSP restrictions.  After obtaining the result of the network request in the hidden page, the content of the response is directly written in the page with CSP restriction to complete the bypass loading.  

**Additional context**
![image](https://user-images.githubusercontent.com/34703535/144349538-0f5b1a84-1662-4305-8d50-2df605e7f3ad.png)

**Comment by Kholid060** [comment]
Have you tried using the preload script?
![image](https://user-images.githubusercontent.com/22908993/144370253-eaadd47e-1b98-4d0a-85a6-713282afc6f0.png)

**Comment by xiaoxuetong** [comment]
I don't see this feature here  ,How can I update and use it
