### ISSUE TITLE
Automatically close Chrome when the script is done.

### ISSUE THREAD

**Issue by bomayso** [Kholid060/automa#151]
I usually run the script with the window like the picture. Close tab function only helps to close the active tab. So the rest of the Automa tab is still there with chrome.
I want after the script is done, Chrome will be closed.
![image](https://user-images.githubusercontent.com/25388131/144526719-b5cecdc3-8b96-4d65-8f00-f8ce4e229d12.png)

**Comment by Kholid060** [comment]
In the close tab block, you can write `<all_urls>`

![image](https://user-images.githubusercontent.com/22908993/144550333-0506e5f4-6fa8-4dad-8453-677fe6d4dd90.png)

**Comment by whwh656** [comment]
she means  close chorme browser  rather than close all tab

**Comment by whwh656** [comment]
He means close chorme browser rather than close all tab

**Comment by Kholid060** [comment]
> He means close chrome browser rather than close all tab.

The thing is, the chrome extension has the ability to close the browser process. And the closest thing that currently Automa has to close the browser is by closing all the tabs

**Comment by bomayso** [comment]
Thanks. problem has been resolved.

**Comment by bomayso** [comment]
> > Ý anh ấy là đóng trình duyệt chrome hơn là đóng tất cả các tab.
> 
> Vấn đề là, phần mở rộng chrome có khả năng đóng quá trình trình duyệt. Và điều gần nhất mà Automa hiện tại phải đóng trình duyệt là đóng tất cả các tab
