### ISSUE TITLE
Having a way to pass data to start a trigger

### ISSUE THREAD

**Issue by nakamaruu** [Kholid060/automa#156]
**Is your feature request related to a problem? Please describe.**
When executing a workflow i'd like to pass in some data, for example, a string

**Describe the solution you'd like**
Maybe in the extension dropdown, for each workflow item, add a text input to pass in data

**Comment by Kholid060** [comment]
You can use global data to do that. And to access it you can write `{{ globalData }}`

![image](https://user-images.githubusercontent.com/22908993/144677467-e2375c91-f22e-40a8-b2af-1807803d6b38.png)
![image](https://user-images.githubusercontent.com/22908993/144677592-3e8b1eb2-8e8b-4a9c-833b-92f95da03ec3.png)
![image](https://user-images.githubusercontent.com/22908993/144677862-cfefffc8-17bf-4088-873f-23543d0e4a9f.png)

**Comment by nakamaruu** [comment]
Thanks, that's really helpful!
