### ISSUE TITLE
copy link pass to new tab

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#166]
**Is your feature request related to a problem? Please describe.**
target url :   https://app.modaiyun.com/share-token/1467778410049622016?source=copylink

![image](https://user-images.githubusercontent.com/20383505/144815953-959b6892-5a97-4043-b7bb-04909b33b917.png)

How can we click this button' url  and  paste  this copy link to new tab 
![image](https://user-images.githubusercontent.com/20383505/144816414-d3642c1d-c5bc-4f22-9de3-0b25c619fc76.png)

**Comment by Kholid060** [comment]
You can use javascript block to read the text from the [clipboard](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#using_the_clipboard_api_2).

```js
navigator.clipboard.readText().then((url) => {
  automaNextBlock({ url })
})
```
But you need to allow the website to access the clipboard
![image](https://user-images.githubusercontent.com/22908993/145127181-e142b7a1-418d-4f03-86b8-06ddc5859feb.png)

[clipboard.txt](https://github.com/Kholid060/automa/files/7672450/clipboard.txt)

**Comment by whwh656** [comment]
Thanks,it works! @Kholid060

**Comment by whwh656** [comment]
done!
