### ISSUE TITLE
javascript eventlistener 

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#167]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/20383505/145006812-bb276895-a625-4339-a401-976adfb67552.png)
[electriccopy1.txt](https://github.com/Kholid060/automa/files/7667317/electriccopy1.txt)

chrome console can catch clickeventlistener  but Automa no effect

**Comment by Kholid060** [comment]
It's because you add the click event listener after the click block is executed. You can use the code in https://github.com/Kholid060/automa/issues/166#issuecomment-988378420 to get the URL and pass it to the new tab block

**Comment by whwh656** [comment]
done!

**Comment by whwh656** [comment]
repeat question #166
