### ISSUE TITLE
add workflow

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#171]
**Describe the bug**

![image](https://user-images.githubusercontent.com/20383505/145571733-687ad2a2-6e30-4908-9784-443ccebc7c6d.png)

1 input name and press enter  
2 don‘t click add 
3 This box don't disappear; when workflow add successfull!

**Comment by Kholid060** [comment]
That's weird, it's working well when I tested it. Can you screenshot the console tab in the devtools when you press enter in the input?

**Comment by whwh656** [comment]
v0.8.3 is normal

**Comment by whwh656** [comment]
done
