### ISSUE TITLE
Trigger event

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#172]
I am comfused about Trigger event of mousemove
[test.txt](https://github.com/Kholid060/automa/files/7693635/test.txt)
i want to rotate the cube when i mousemove the canvas but i don‘t how to use  mouse event

**Comment by Kholid060** [comment]
Update the extension into v0.8.3 and try the workflow below 

[test (2).txt](https://github.com/Kholid060/automa/files/7696197/test.2.txt)

**Comment by whwh656** [comment]
greate,it works! @Kholid060
