### ISSUE TITLE
mouserover

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#178]
[mouseover.txt](https://github.com/Kholid060/automa/files/7698582/mouseover.txt)

I want to hover project_2 card to appear  a black background

![image](https://user-images.githubusercontent.com/20383505/145709433-71433178-bcf6-48fa-a130-20b6a7c2a780.png)

![image](https://user-images.githubusercontent.com/20383505/145709413-fc53fbd9-1aaf-4c99-bb21-b91659bbeaee.png)

**Comment by Kholid060** [comment]
It uses CSS to get that background color effect when hovering, so the `mouseover` event won't be affected.

**Comment by whwh656** [comment]
Is there any other way to solve it？ please

**Comment by Kholid060** [comment]
There's no other way to force the hover state of CSS

**Comment by whwh656** [comment]
DONE
