### ISSUE TITLE
can we create collection in workflow 

### ISSUE THREAD

**Issue by MADCAZ** [Kholid060/automa#18]
**Is your feature request related to a problem? Please describe.**
- I try to use for test my projects and I can't group workflow for each project.

**Describe the solution you'd like**
- If we have collection for test each project. It would be good.
- can we run workflow in collection like example. Register > Login > Test Add Some Data.
- after run can we export test result in collection

**Comment by Kholid060** [comment]
I think this feature will be complicated to implement, but I will try to add this feature in the next version.
