### ISSUE TITLE
Fullscreen not working on MAC

### ISSUE THREAD

**Issue by namhong1412** [Kholid060/automa#19]
**Fullscreen not working on MAC**
Your extension is very good, but when I click the full-screen button, is not working. I using a MacBook OS Monterey.

**Comment by bxb100** [comment]
This button function is zoom reset
![image](https://user-images.githubusercontent.com/20685961/140636564-597b4acb-8a64-40eb-b616-57599a21e809.png)

**Comment by Kholid060** [comment]
Like what @bxb100 said, it's not a button for fullscreen but for reset zoom.
