### ISSUE TITLE
Possible bug in dataColumns operations. 

### ISSUE THREAD

**Issue by fnfontana** [Kholid060/automa#190]
**Describe the bug**
When I enter {{dataColumns@n.data}}, the output is something like [{"test":"Captured Text"}] instead of Captured Text.  When I started to use Automa some days ago this didn't happen, just yesterday this strange behavior begins to happen.

**To Reproduce**
1. Use the block Get Text to get some text of the web and save it to a Data Column
2. Then use the block Forms to output this data by using the {{ dataColumns@0.test }} in a text field of another site
4. The output is [{"test":"Captured Text"}]  instead of just the string Captured Text

**Expected behavior**
I expected to have the string output displayed correctly in my workflows instead of this kind of raw data. 
Automa should output in the form: Captured Data instead of [{"test":"Captured Data"}]

**Screenshots**
> In the screenshot below, the output should be just Highway to Hell

![Screenshot_Bug_Automa](https://user-images.githubusercontent.com/8870142/145995797-c467e89f-c3ae-41ff-ae8a-7aaea8e2cc44.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Additional context**
I'm a new user to Automa and started to use this week. In the first days everything works fine, but yesterday this bug suddenly starts to happen, even to my old workflows that used to works properly.

I have exported the workflow that I made to test this bug. I have tested in another computer and another browser also and have the same problematic output:
[Test dataColumns.zip](https://github.com/Kholid060/automa/files/7711467/Test.dataColumns.zip)

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/146006480-4fecafb7-4b86-4ad9-82a4-b38649000882.png)
try it !

**Comment by fnfontana** [comment]
Thank you!

I have tested here...

> If I enter ***@***.***}} >> the output is displayed correctly.


But if I try to store multiple texts in one dataColomn, like an array, the
output is displayed in a weird way. The output is something like:

> ***@***.***}} and ***@***.***}} >> [{"teste":"Highway
> to Hell"},{"teste":"Back in Black"}] and [{"teste":"Highway to
> Hell"},{"teste":"Back in Black"}].


Is working if the text is stored in multiple dataColumns, like teste_1;
teste_2; teste_3 and so on...

Em ter., 14 de dez. de 2021 às 10:23, whwh656 ***@***.***>
escreveu:
