### ISSUE TITLE
Close chrome when the workflow timeout is over.

### ISSUE THREAD

**Issue by bomayso** [Kholid060/automa#197]
I want after the Workflow timeout, chrome will close by itself to free up memory because I use a lot of chrome profiles
![Capture2](https://user-images.githubusercontent.com/25388131/146377770-f14a6f61-a78c-4a10-91b3-f6e9d7c007ce.PNG)

I want to disable the timeout notification like the image. I run a lot of profiles and it shows up too much.
![Capture](https://user-images.githubusercontent.com/25388131/146378102-1e9d17c7-f383-4600-af8d-ea8047e6e24b.PNG)

**Comment by Kholid060** [comment]
Have you update the extension to the latest version?

**Comment by bomayso** [comment]
> > Tôi muốn tắt thông báo thời gian chờ như hình ảnh. Tôi chạy rất nhiều hồ sơ và nó hiển thị quá nhiều.
> 
> Bạn đã cập nhật tiện ích mở rộng lên phiên bản mới nhất chưa?

sure. this is automatic for chrome.
