### ISSUE TITLE
cannot execute javascript code

### ISSUE THREAD

**Issue by thankwsx** [Kholid060/automa#199]
version: 0.9.6
trigger->new tab->javascript code

then log panel show javascript code is error.

and the website which opened doesn't have any script tag with the automa-custom-js id.

I don't know why.

how to import the automa-custom-js?

![image](https://user-images.githubusercontent.com/90209/146393289-c0ed5b53-e771-4476-88b0-4961330e6e0b.png)

![image](https://user-images.githubusercontent.com/90209/146393410-a6ca75fd-22f6-4bc5-a5db-33be856d0f67.png)

**Comment by yarekc** [comment]
Same: No idea how to execute a simple alert("hello world")

**Comment by bboisset** [comment]
Same here ! No able to do nothing with JS block. Everything else work well
