### ISSUE TITLE
Webhoook support

### ISSUE THREAD

**Issue by bxb100** [Kholid060/automa#20]
**Is your feature request related to a problem? Please describe.**
support string template to convert data to json or url-encode for webhook param

**Describe the solution you'd like**
omit

**Describe alternatives you've considered**
omit

**Additional context**
WIP

**Comment by bxb100** [comment]
Working on it, wait my pr...

**Comment by Kholid060** [comment]
Oh, thanks, can't wait to see your PR 😃
