### ISSUE TITLE
Keyboard shortcut not working?

### ISSUE THREAD

**Issue by LionelSelie** [Kholid060/automa#204]
**Describe the bug**
When using the keyboard shortcut trigger, it does not seem to initiate a workflow when using the key combo

**To Reproduce**
1. Set up workflow like this: https://cdn.zappy.app/80d80148cdb6a0ba80f76a42a345b47d.png
2. Save and refresh the page
3. Hit key combo
4. No workflow is kicked off

Note: I can manually play the workflow, and then everything works as intended

**Expected behavior**
Workflow is kicked off

**Screenshots**
This is in Zendesk, so not sure if this is a Zendesk specific thing?

**Desktop (please complete the following information):**
 - OS: 12.0.4 macOS

**Additional context**
I might misunderstand how to use the keyboard shortcut trigger, but I was not able to find any documentation on how to set that up. This could very well be user error and not a bug. Thanks for looking into it!

**Comment by Kholid060** [comment]
Have you tried using another keyboard shortcut? Like `shift+n` for example

**Comment by LionelSelie** [comment]
Hi there!

Yes, I did and it seems this is not responding (not seeing any success or error logs).

I'm not sure if I set it up incorrectly, but I'm excited about the idea to make it work.

**Comment by LionelSelie** [comment]
Hi @Kholid060—I was able to switch it out to other keyboard shortcuts and that seems to have done the trick. The issue I'm having now is that the item I want to click on changes its id. Sometimes it's `#downshift-8-item-0`, then it changes to `#downshift-42-item-0`, etc.

The only thing that remains constant is the text used, so perhaps that can be used to click on an element?

![](https://cdn.zappy.app/5b9b83e59e4cf1975840b7f428a6e38d.png)

If so, could you please let me know how to do that?

**Comment by Kholid060** [comment]
> Hi @Kholid060—I was able to switch it out to other keyboard shortcuts and that seems to have done the trick. The issue I'm having now is that the item I want to click on changes its id. Sometimes it's `#downshift-8-item-0`, then it changes to `#downshift-42-item-0`, etc.
> 
> The only thing that remains constant is the text used, so perhaps that can be used to click on an element? Or maybe the tracking ID can be used?
> 
> ![](https://camo.githubusercontent.com/686c609133d77194181589db7ee0472b4caa65d6f0c40c0937545a9d6f23f032/68747470733a2f2f63646e2e7a617070792e6170702f35623962383365353965346366313937353834306237663432386136653338642e706e67)
> 
> If so, could you please let me know how to do that?

Try use XPath and input `//li[text()='Next ticket in view']` as the element selector.

**Comment by LionelSelie** [comment]
Hmmm... that didn't seem to do the trick, unfortunately. I'm pretty sure this is possible and it just depends on the input, but it's definitely challenging to set it up. I appreciate the support a lot though! I'll try to see if I can get some help from colleagues to make this work. If not, and we can do a screen share at one point, I would be open for that as well. Happy holidays!

**Comment by Kholid060** [comment]
When you click the "Next ticket in view" element, does the `data-test-action="next_ticket"` change? If it's not changed, you can use it as the selector, and to do that, select "CSS selector" and write `[data-test-action="next_ticket"]`

**Comment by LionelSelie** [comment]
Just had a chance to check it—and yes, that did the trick!

Thanks so much for your help, this did exactly what I wanted it to do, thanks so much! I'll close it out <3
