### ISSUE TITLE
javascript not running

### ISSUE THREAD

**Issue by kession** [Kholid060/automa#208]
**version:0.9.7**

javascript node run error.  use the latest version
chrome version: 96.0.4664.110 (x86_64)

**Screenshots**
![image](https://user-images.githubusercontent.com/1208360/146705780-0a8ffcfb-2076-4f89-86a0-d99a1b1edc3e.png)

**Comment by whwh656** [comment]
display your whole workflow or paste your javascript code in issue

**Comment by kession** [comment]
![image](https://user-images.githubusercontent.com/1208360/146720911-74250adb-1868-4e3b-b2a9-327eb5eb87c6.png)
JAVASCRIPT CODE:
`console.log("Hello world2!");
`

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/146725118-611458d6-7898-49d3-83be-efc40f9b1ed0.png)
![image](https://user-images.githubusercontent.com/20383505/146725136-a339c913-7391-43ad-9900-5933b2a74d9f.png)
I tried. It's normal

**Comment by kession** [comment]
> ![image](https://user-images.githubusercontent.com/20383505/146725118-611458d6-7898-49d3-83be-efc40f9b1ed0.png) ![image](https://user-images.githubusercontent.com/20383505/146725136-a339c913-7391-43ad-9900-5933b2a74d9f.png) I tried. It's normal

It worked before.  I have tried restart chrome，readd automa extention.
all javascript in workflow execute failed now.

**Comment by kession** [comment]
The problem solved!
Edit the workflow remove the javascript node, replace a new one, paste the code , It works.
---
ps. I export the workflow  and reinstall automa extention, reimport the workflow.   That is not valid way.
