### ISSUE TITLE
Firefox Version

### ISSUE THREAD

**Issue by Beatzoid** [Kholid060/automa#21]
First, this is an amazing extension, and good job for making it. I was wondering if a Firefox version was planned. I know it might be a little difficult because of Firefox's increased security with extensions, but it would be great if you could at least consider it.

**Comment by Kholid060** [comment]
I don't have a plan to add the firefox version of this extension, because it'll be so much to handle. But if everything is going well, I'll consider adding it in the future.

**Comment by Beatzoid** [comment]
Sounds good, thanks!

**Comment by LakeishaKowalczyk** [comment]
+1

**Comment by Lemonawa** [comment]
+1
```
ERROR: The "proxy" permission requires "strict_min_version" to be set to "91.1.0" or above. Please update your manifest.json version to specify a minimum Firefox version.
```
Maybe just one error

**Comment by elementh** [comment]
Would love to have a Firefox version of this awesome extension :)

**Comment by Kholid060** [comment]
Good news! Automa is now available in Firefox, you can get it by following this link 👇
https://addons.mozilla.org/en-US/firefox/addon/automa/

This release is in Beta, and if you find a bug or something that's not working, you can open an issue in this repository.

**Comment by Lemonawa** [comment]
> Good news! Automa is now available in Firefox, you can get it by following this link 👇 https://addons.mozilla.org/en-US/firefox/addon/automa/
> 
> This release is in Beta, and if you find a bug or something that's not working, you can open an issue in this repository.

Good. It works!!!
