### ISSUE TITLE
clone this project 

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#210]
branch:main
![image](https://user-images.githubusercontent.com/20383505/146890381-3b2fdc3a-20b8-4a3a-88a9-895ea9a17c91.png)

**Comment by Kholid060** [comment]
Create  a `secret.development.js` js at the root file

**Comment by whwh656** [comment]
> Create a `secrets.development.js` js at the root folder

Thanks,t work
![image](https://user-images.githubusercontent.com/20383505/146895687-30ee14c6-993c-4a21-a732-80536bea5c3e.png)
Automa doesn't a web project, how can i debug code in my own develop environment, or i must yarn build and install to chrome to debug?

**Comment by Kholid060** [comment]
To debug chrome extension
1. Run `yarn dev` or `npm run dev`
2. Open `chrome://extensions/` in chrome
3. Enable Developer mode on the top right
4. Drag and drop `build` to the `chrome://extensions/` page
