### ISSUE TITLE
ask for help, get text length 

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#211]
![image](https://user-images.githubusercontent.com/20383505/146930571-3a0ba0fa-ac0a-4b49-93f6-841b1b834cfc.png)

![image](https://user-images.githubusercontent.com/20383505/146930485-6fb38f85-9b5c-4d86-af04-1fba37af22f5.png)

![image](https://user-images.githubusercontent.com/20383505/146930839-fb982a10-b017-4930-a99b-840468f9f969.png)

How can i get the length of variable of   four's length in javasciprt code block?

**Comment by Kholid060** [comment]
In the javascript code block 
```js
const textlen = automaRefData('dataColumns', '0.four').length;
```

**Comment by whwh656** [comment]
greate ! it works!
