### ISSUE TITLE
How to get loop variable.

### ISSUE THREAD

**Issue by chanben2005** [Kholid060/automa#212]
my idea is :
1. Open the website for https://github.com/Kholid060/automa
2. Get the .mt-2:nth-child(**_i_**) text.
I want to set the **_i_** loop 0 to 10.
 ![image](https://user-images.githubusercontent.com/34121011/147036236-68ff581f-d015-4c47-9050-4b96ffef405e.png)
3. If the text is MIT License, it will click.
![image](https://user-images.githubusercontent.com/34121011/147036616-08b466fb-e006-4212-b9ad-78ab63d6948c.png)

How can i set the **_i_** variable?

Another question, for example, I open A and B website. How can B website switch A website?

Have a good day!

**Comment by Kholid060** [comment]
You can write `{{ prevBlockData }}` as the first value in the condition input.

![image](https://user-images.githubusercontent.com/22908993/147040731-213c89a8-e19b-4090-b9b4-f46544c1387e.png)

Currently, there's a bug where the fallback output doesn't show up when there's only one condition. And for now, add another condition like the image above.

> Another question, for example, I open A and B website. How can B website switch A website?

Automa doesn't have the ability to switch between tabs right now

**Comment by chanben2005** [comment]
Some suggest.
1.  I can edit after I am add column
![image](https://user-images.githubusercontent.com/34121011/147099486-6a59c9f7-1d2b-411f-b83b-ebe51a221421.png)

2. The conditions element can make description.
![image](https://user-images.githubusercontent.com/34121011/147099874-786ed7de-8a1a-4270-a40a-1a3b85b21c7d.png)

Some question.
Can make like javascript?
1. Can I customize Loop data number?

for example:
```
var data = [Readme, License, MIT License, 3k stars, 45 watching, 255 forks];

for (i = 0; i < data.length ; i++) {
}
```
![image](https://user-images.githubusercontent.com/34121011/147101018-139f8476-a16c-4fd0-8753-f2bd31da7317.png)

2. How can give data number and set break or continue?
for example:
```
for (i = 0; i < data.length ; i++) {
if ( i = 2) {
var a = i;
break;
}
}
```

**Comment by chanben2005** [comment]
Some question.
Can make like javascript?
1. Can I customize Loop data number?

for example:
```
var data = [Readme, License, MIT License, 3k stars, 45 watching, 255 forks];

for (i = 0; i < data.length ; i++) {
}
```
![image](https://user-images.githubusercontent.com/34121011/147101018-139f8476-a16c-4fd0-8753-f2bd31da7317.png)

2. How can give data number and set break or continue?
for example:
```
for (i = 0; i < data.length ; i++) {
if ( i = 2) {
var a = i;
break;
}
}
```

Thank you for spending time answering my questions.

**Comment by chanben2005** [comment]
I have add another condition, but it ignore condition.
I am set condition If the text is MIT License, it will click MIT License.
but now the text is Readme, it will click Readme.
Is it bug?

![image](https://user-images.githubusercontent.com/34121011/147107112-6000f8b9-1f5f-4339-a837-063e9877f240.png)

Replace the extension from txt to json, you can get this example.
[click test.txt](https://github.com/Kholid060/automa/files/7763130/click.test.txt)

**Comment by Kholid060** [comment]
> Some suggest.
> 
> 1. I can edit after I am add column
>    ![image](https://user-images.githubusercontent.com/34121011/147099486-6a59c9f7-1d2b-411f-b83b-ebe51a221421.png)
> 2. The conditions element can make description.
>    ![image](https://user-images.githubusercontent.com/34121011/147099874-786ed7de-8a1a-4270-a40a-1a3b85b21c7d.png)

1. I disabled the edit because I'm using the name of the column as the ID. And if the editing is enabled, it may lead to duplication of the column.

**Comment by Kholid060** [comment]
>I have added another condition, but it ignores the condition.
>I am set condition If the text is MIT License, it will click MIT License.
>but now the text is Readme, it will click Readme.
>Is it a bug?

No, it's not a bug. It's because the condition block is execute the condition from top to bottom which in the first condition, you can see it compare between an empty value and the value is `true` because it's equals. And try to check the element selector, if it's the correct selector for the element or not.

> If I set the line on the second position, it only loop one time
Check the logs of the workflow, check whether is a success or an error.

**Comment by chanben2005** [comment]
Thanks for your help.
