### ISSUE TITLE
How to get random element?

### ISSUE THREAD

**Issue by xkonglong** [Kholid060/automa#213]
for example:

I want receive free games at EPIC.

https://www.epicgames.com/store/en-US/free-games?lang=en-US

![image](https://user-images.githubusercontent.com/9131496/147049460-f91a05c9-524f-4d2b-b711-f5d453284d0a.png)

**Comment by Kholid060** [comment]
If you want to get the link to the free game, you can use the XPath selector to do it. And in this case, the XPath would be `//span[text()='Free Now']/ancestor::a`
