### ISSUE TITLE
CAN'T IMPORT THE WORKFLOWS

### ISSUE THREAD

**Issue by 547555909** [Kholid060/automa#214]
MAC OS 10.15.7
CHROME96.0.4664.110

**Describe the bug**
CAN'T IMPORT THE WORKFLOWS

**To Reproduce**
1. Go to 'workflows'
2. Click on 'IMPORT'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
MAC OS 10.15.7
CHROME96.0.4664.110
AUTOMA VESION:0.9.7

**Additional context**

**Comment by Kholid060** [comment]
Can take a screenshot of the console tab of the devtool (`ctrl+shift+I`) when you try to import a workflow?

**Comment by 547555909** [comment]
您发给我的邮件我已收到，我会尽快回复您的

**Comment by 547555909** [comment]
> Can take a screenshot of the console tab of the devtool (`ctrl+shift+I`) when you try to import a workflow?

OK,I will send screenshot for you at 27-12-2021,i'm now on vacation.

**Comment by 547555909** [comment]
<img width="810" alt="automa-error" src="https://user-images.githubusercontent.com/19320063/147432413-583ea14b-6f13-4dfe-9684-01646f6d989f.png">
This is the screenshot,my import workflows file is this:https://raw.githubusercontent.com/547555909/automa-workflows/main/workflows/%E7%BD%91%E6%98%93%E4%BA%91%F0%9F%8E%B5-%E8%AF%A6%E6%83%85%E9%A1%B5-%E5%A4%96%E9%93%BE%E6%92%AD%E6%94%BE%E6%88%96%E4%B8%8B%E8%BD%BD.json
