### ISSUE TITLE
how to get `globalData` in `JavaScriptCode`?

### ISSUE THREAD

**Issue by shaoxyz** [Kholid060/automa#217]
Have no idea about how to access globalData in `JavaScriptCode`.

![image](https://user-images.githubusercontent.com/26154330/147382542-f82d58c5-0299-4776-96ac-ba5dbd8f74e4.png)

This would absolutely cause `SyntaxError: Unexpected token '{'`

More examples would be better.

Thanks very much~

**Comment by Kholid060** [comment]
Use the `automaRefData` function, for example 
```js
console.log(automaRefData('globalData', '0.key'))
```
