### ISSUE TITLE
Saving screenshots in a specific folder

### ISSUE THREAD

**Issue by br0gio** [Kholid060/automa#219]
I'd like to be able to save screenshots in a specific folder instead of my download one, it would also be nice if you could have the date that the screenshot was made in the file name

For example: 26-12-2021.png (in specified folder)

**Comment by Kholid060** [comment]
> I'd like to be able to save screenshots in a specific folder instead of my download one

It's not possible to save a screenshot in a specific folder because the chrome extension doesn't have access to the file system
