### ISSUE TITLE
Is it possible to pass dynamic global data when executing another workflow?

### ISSUE THREAD

**Issue by signals2** [Kholid060/automa#222]
Thanks for this great extension.
It seems that the global data pass to workflow can only be some static json string, how can i pass some dynamic json string generated by a javascript code block?
![call-workflow](https://user-images.githubusercontent.com/7675629/147446936-59bea1a8-8bef-4dbe-a1db-75afa6083347.png)

**Comment by Kholid060** [comment]
It's currently not possible, but I'll add this feature in the next update.

**Comment by signals2** [comment]
thanks, but what's the plan for next update, it's an anticipated useful enhancement ;)

**Comment by Kholid060** [comment]
This feature will be available in v0.11.0, and this version is right now is in the review process in the chrome webstore.
