### ISSUE TITLE
get text to webhook

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#223]
![image](https://user-images.githubusercontent.com/20383505/147454343-7aac26a4-7bd5-4b7a-8213-3666a158226a.png)
![image](https://user-images.githubusercontent.com/20383505/147454444-5e5491f0-c0b8-496e-9d83-f0167f167a59.png)
![image](https://user-images.githubusercontent.com/20383505/147454556-038c0066-b240-40e4-9df9-25229c11449f.png)

**Comment by Kholid060** [comment]
Try 
```json
"text": {
  "content": "{{dataColumns@count}}"
}
```

**Comment by whwh656** [comment]
It works!
