### ISSUE TITLE
https://automa.vercel.app/ looks very good but won't let me publish a second workflow

### ISSUE THREAD

**Issue by MagEpub** [Kholid060/automa#228]
### Discussed in https://github.com/Kholid060/automa/discussions/227

<div type='discussions-op-text'>

<sup>Originally posted by **MagEpub** December 27, 2021</sup>
It seems to work fine, but when I tried to add a second workflow I couldn't find a way.

I have four of them here:

https://github.com/MagEpub/Automa3

That I wanted to upload</div>

**Comment by Kholid060** [comment]
Can you take a screenshot of the console table of the dev tools (`ctrls+shift+i`) when you try to share the workflow?

**Comment by Kholid060** [comment]
I've seen the marketplace and it seems like you have successfully shared all the workflows

**Comment by MagEpub** [comment]
Yes, I discovered the correct sequence and posted my answer in the
discussion.  Thanks for your email, I'm sure you must be very busy.
