### ISSUE TITLE
Delay block doesn't finish

### ISSUE THREAD

**Issue by Eliasyoussef47** [Kholid060/automa#234]
**Describe the bug**
When using the delay block in one of the next ways:

![image](https://user-images.githubusercontent.com/31613492/147674320-570321a7-d864-4006-bcb5-dcf599bd672f.png)

![image](https://user-images.githubusercontent.com/31613492/147674300-c97638eb-e7bd-489e-a1e1-82c46bd1fcc5.png)
The workflow gets stuck at delay:
![image](https://user-images.githubusercontent.com/31613492/147674272-2a27272b-2308-4f6e-aa53-d0237360d857.png)

**To Reproduce**
1. Make a new workflow
2. Edit the trigger to start when visiting a website like so:
![image](https://user-images.githubusercontent.com/31613492/147676348-a1f88bd7-3e7b-4579-a11b-ac69af88bb9f.png)
3. Add "Active tab", "Delay" and "JavaScript  code" blocks
4. Go to https://calendar.google.com/calendar

**Expected behavior**
The workflow to work.

**Desktop (please complete the following information):**
 - OS: Chrome 96.0.4664.110
 - Automa version: 0.11.0

**Additional context**
The JavaScript code should click on the calendar with the name "School deadlines":
![image](https://user-images.githubusercontent.com/31613492/147676779-9429f4b3-22fd-4c5c-a350-028e57351c28.png)
This is the code:
```JavaScript
console.log("Gonna click");
let elementsArray = Array.from(document.querySelectorAll("#dws12b > div > div > li > label > div.NI2kfb.qZvm2d-ibnC6b-bN97Pc.DX3x9d > span"));
let foundElement = elementsArray.find(e => e.innerText == "School deadlines");
foundElement.click();
automaNextBlock()
```

**Comment by Kholid060** [comment]
Try to stop the workflow first and then visit the https://calendar.google.com/calendar website. If it still not working, can you take a screenshot of the console tab of the Automa background page? And to do that, open `chrome://extension` in a new tab and click the "Background page" of the Automa extension.
![image](https://user-images.githubusercontent.com/22908993/147714885-98fa444f-dc46-4f53-8a15-d28df2524fd0.png)

**Comment by Eliasyoussef47** [comment]
v0.12.0 seems to have fixed this problem. Thank you @Kholid060.
