### ISSUE TITLE
Is it possible to take desktop screenshot?

### ISSUE THREAD

**Issue by signals2** [Kholid060/automa#235]
Now the take screenshot block works good, however the result image contains only the page part, is it possible to take the screenshot of entire screen? 
I've tried to take desktop screenshot through a javascript code block using the getDisplayMedia API,  it's not perfect, the annoying permission window shows up everytime,  ...

**Comment by Kholid060** [comment]
> Now the take screenshot block works good, however the result image contains only the page part, is it possible to take the screenshot of entire screen?

Unfortunately, it's not possible to take a screenshot of the entire desktop screen using chrome extension.
