### ISSUE TITLE
dataColumns type Array 

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#236]
![image](https://user-images.githubusercontent.com/20383505/147802944-99472e68-229f-4163-8ec1-6051a0f95f0c.png)

![image](https://user-images.githubusercontent.com/20383505/147802939-d3ff4101-dd33-45f7-9add-394d8db1d298.png)

![image](https://user-images.githubusercontent.com/20383505/147802923-947ba5e8-8b13-42ce-a519-a2b2e3a31fa1.png)
![image](https://user-images.githubusercontent.com/20383505/147802981-15fa10a1-88a6-46d2-80e5-18642fe603fb.png)
![image](https://user-images.githubusercontent.com/20383505/147803024-779dc032-617f-4c9d-9de8-53efb17733e2.png)

**Comment by whwh656** [comment]
Automa v0.12.0
![image](https://user-images.githubusercontent.com/20383505/147853012-22054ff7-c294-4da4-808a-20039d9e1949.png)
![image](https://user-images.githubusercontent.com/20383505/147853035-4744bf53-9011-45f5-bfc9-90d0a56b0073.png)
![image](https://user-images.githubusercontent.com/20383505/147853044-c2ce086b-ad25-49e0-9e71-e910e87c444a.png)

I want to send this array of fivetext at once  but failed

**Comment by Kholid060** [comment]
try 
```json
{
  "msgType": "markdown",
  "markdown": {
    "text": {{ dataColumns@text }}
  }
}
```

**Comment by whwh656** [comment]
> try
> 
> ```json
> {
>   "msgType": "markdown",
>   "markdown": {
>     "text": {{ dataColumns@text }}
>   }
> }
> ```

it doesn't work

**Comment by Kholid060** [comment]
That weird, it's working in my testing. If it's still not working try to remove and then add the webhook block.
[array.txt](https://github.com/Kholid060/automa/files/7798847/array.txt)
