### ISSUE TITLE
element exists block not work as expected

### ISSUE THREAD

**Issue by signals2** [Kholid060/automa#237]
**Describe the bug**
![微信截图_20211231220720](https://user-images.githubusercontent.com/7675629/147828571-fba58be0-72b4-4e34-8fce-837c745dce69.png)

**To Reproduce**
1. new workflow
2. add an element exists block
3. add a normal next block
4. add a fallback block
5. execute the flow

**Expected behavior**
Either normal flow or fallback  block should be executed, however it stops with error message: "Could not establish connection. Receiving end does not exist."

**Screenshots**
workflow definition as below:
![微信截图_20211231223853](https://user-images.githubusercontent.com/7675629/147828657-c6547ad1-c6b5-4d2a-bc33-35cb1b4677b7.png)

**Desktop (please complete the following information):**
 - OS: windows10, microsoft edge 
 - Version 96.0.1054.62 with automa-0.11.0

**Additional context**
nothing

**Comment by Kholid060** [comment]
Can you click the log and screenshot the block that error like the image below
![image](https://user-images.githubusercontent.com/22908993/147843334-acda8075-c1c1-4517-9ae8-d60d64715ec2.png)

**Comment by signals2** [comment]
Happy new year!
It seems that the element exists block throws some exception.
![image](https://user-images.githubusercontent.com/7675629/147845806-2c70413c-a0f2-4259-90a8-caeeb10a475e.png)

I can not find any further error details in the log entry.

**Comment by Kholid060** [comment]
Happy new year to you as well,

When the click element block was executed, does it close or update the tab?

![Untitled](https://user-images.githubusercontent.com/22908993/147846729-b84f969b-54c7-4786-bafc-5e63226dc791.png)

**Comment by signals2** [comment]
The click element block clicks a search button, and triggers an async ajax query, the following element exists block just waits the result list to show in the result div of current page, and the tab remains no update.

**Comment by signals2** [comment]
> Happy new year to you as well,
> 
> When the click element block was executed, does it close or update the tab?
> 
> ![Untitled](https://user-images.githubusercontent.com/22908993/147846729-b84f969b-54c7-4786-bafc-5e63226dc791.png)

The element exists block works good after i upgrade the extension to 0.12.1, thanks for your quick fix:)
