### ISSUE TITLE
How do I correctly format an object in Javascript to pass to Loop Data to use with DataColumns?

### ISSUE THREAD

**Issue by pholcroft** [Kholid060/automa#245]
I have a successful workflow with loop data using custom data imported via CSV. I need to tweak this to prompt the user to import the CSV as part of the workflow. To achieve this I have placed a JavaScript block before the loop data block which prompts the user to import a CSV file and parse it, this works. But no matter how I pass the data, it is not available to the next block. The data itself appears to be identical to what appeared in custom data when viewed via popup.

Reading the source code it appears I may need to create a specific type of object to pass the data, rather than just pass the array of data or the string version of it. I have spent days trying different ways to figure this out, but I can't get it to work.

Here is the basic version of one of my attempts to get this to work:

```javascript
var input = $(document.createElement('input'));
  input.attr("type", "file");
  input.on('change', function() {
    var csvFile = input[0].files[0];
    var ext = csvFile.name.split(".").pop().toLowerCase();

    if (ext != "csv") {
      alert('upload csv');
      return false;
    }
    if (csvFile != undefined) {
      reader = new FileReader();
      reader.onload = function(e) {
        var data = Papa.parse(e.target.result, {
			     header: true
		      }).data;
        var dataStr = JSON.stringify(data, null, 0);
        alert(dataStr); // This appears identical to the view of custom data when importing the same CSV.
        automaNextBlock(dataStr);
      }
      reader.readAsText(csvFile);
    }
  });
  input.trigger('click');
```

CSV File:
```
MembershipNo,Fee,FeeDescription
123456,"1.00","General Fees"
111111,"1.23","Lottery"
222222,"15.00",Raffle
```

Loop data - custom data - Import CSV:
`[{"MembershipNo":"123456","Fee":"1.00","FeeDescription":"General Fees"},{"MembershipNo":"111111","Fee":"1.23","FeeDescription":"Lottery"},{"MembershipNo":"222222","Fee":"15.00","FeeDescription":"Raffle"}]`

JSON Stringify Alert of dataStr (JavaScript imported CSV):
`[{"MembershipNo":"123456","Fee":"1.00","FeeDescription":"General Fees"},{"MembershipNo":"111111","Fee":"1.23","FeeDescription":"Lottery"},{"MembershipNo":"222222","Fee":"15.00","FeeDescription":"Raffle"}]`

I have been trying to find the part in the source code where the loopdata is converted into a datacolumn, or how it reads the data in loop data. I have tried creating an object with a "BlockId" and a "Data" Object inside without success. I know the answer is in the source code somewhere, but I am really struggling with this and I would appreciate some help.

**Comment by pholcroft** [comment]
With further investigation of the source code I understand better how [reference data](https://github.com/Kholid060/automa/wiki/Features#reference-data) works and I have come to the conclusion that I cannot use [automaNextBlock(data)](https://github.com/Kholid060/automa/wiki/Blocks#automanextblockdata) as data passed this way is only accessible by prevBlockData which isn't an option to use with [LoopData](https://github.com/Kholid060/automa/wiki/Features#loop-data).

Therefore I think I need to use dataColumns and [automaRefData](https://github.com/Kholid060/automa/wiki/Blocks#automarefdatakeyword-path), but so far I have been unable to successfully update the dataColumns using [automaRefData](https://github.com/Kholid060/automa/wiki/Blocks#automarefdatakeyword-path). I can get it working with a two dimensional array `{"MembershipNo":"123456","Fee":"1.00","FeeDescription":"General Fees"}` but not with the full array of objects.

I would appreciate an example of how to update dataColumns with arrays of objects in javascript to use with LoopData using automaRefData. Is this even possible?

Alternatively since I started this journey you have added the google spreadsheet option, so perhaps instead I update the spreadsheet, then use it as the source for Loop Data, but it seems like a long way around the issue.

I would like to update the documentation regarding refence data when I am finished with more examples of using each type of reference data and an explanation of how the data is stored internally, but first I need to full understand it myself.

**Comment by Kholid060** [comment]
Sorry for the late reply,
You can pass an array of objects inside the `automaNextBlock` function, but you need to that Automa will try to check every key of the object whether the key is defined in the data columns or not.

https://github.com/Kholid060/automa/blob/3426e87e7453939e9daab50f2f54f35686bec329/src/background/workflow-engine/blocks-handler/handler-interaction-block.js#L51-L55
https://github.com/Kholid060/automa/blob/3426e87e7453939e9daab50f2f54f35686bec329/src/background/workflow-engine/engine.js#L163-L187

You can try this workflow as an example and use the CSV file below it, you need to convert the `.txt` to `.json` first and then import it.

[CSV.txt](https://github.com/Kholid060/automa/files/7818613/CSV.txt)
[addresses.csv](https://github.com/Kholid060/automa/files/7818614/addresses.csv)

**Comment by pholcroft** [comment]
This is fantastic thankyou. I did go down this route at one point, but obviously I didn't persist enough. I think my issue was having upper case letters in my CSV header and data columns are forced to lowercase. Also JavaScript isn't my normal language so I wasn't sure if my understanding of the code was correct.

Examples are great and I hope the new repository will solve a lot of misunderstanding.

I have altered the JavaScript code to force headers to lowercase (probably overkill) and created a demo webpage using Github Gists for testing. I did this mainly as a test to find a good way to demonstrate Automa workflows and blocks. I am not sure if I have succeeded on that point as your google.com demonstration was a lot simpler. I did find that jsFiddle is no good due to the sandboxed iframe...

If anyone wants to have a go rename the attached `.txt` file to `.json` and import into Automa. Use the CSV file as the input when prompted.

**Here is the JavaScript block I used to prompt for the CSV file:**
```javascript
var input = $(document.createElement('input'));
  input.attr("type", "file");
  input.on('change', function() {
    var csvFile = input[0].files[0];
    var ext = csvFile.name.split(".").pop().toLowerCase();

    if (ext != "csv") {
      alert('upload csv');
      return false;
    }
    
    if (csvFile != undefined) {
      reader = new FileReader();
      reader.onload = function(e) {
        const config = {
          header: true,
          // Automa does not allow uppercase letters for dataColumns
          // Convert to LowerCase
          transformHeader:function(h) {
            return h.toLowerCase(); 
          }
        };
        var data = Papa.parse(e.target.result, config).data;
        automaNextBlock(data);
      }
      reader.readAsText(csvFile);
    }
  });
  input.trigger('click');
```
**The CSV file:**
```
membershipno,fee,FeeDescription
123456,"1.00","General Fees"
111111,"1.23","Lottery"
222222,"15.00",Raffle
```

**How my Data columns are configured:**
![image](https://user-images.githubusercontent.com/4210486/148400202-7d935bfa-c4b8-4b06-97e2-aab2c8f8ef29.png)

How I referenced the data when inputting to text boxes:
![image](https://user-images.githubusercontent.com/4210486/148401162-b0dbbf17-10fc-47cb-ac53-a79d8cc7aa3d.png)


**The successful demo:**
![image](https://user-images.githubusercontent.com/4210486/148400559-a82185f9-202e-4801-b1cc-e3ee5840e1b6.png)


[Demo JS Csv Import To Loop.txt](https://github.com/Kholid060/automa/files/7822331/Demo.JS.Csv.Import.To.Loop.txt)
[AutomaTestCsvInputToLoop.csv](https://github.com/Kholid060/automa/files/7822335/AutomaTestCsvInputToLoop.csv)
