### ISSUE TITLE
keyboard event 

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#246]
I want to input @ somebody,  I try to  use type character '@xxx' it doesn't work,
How  can I use  keyboard event : shift +2  to  simulate the  event  @

As shown in the picture below
![image](https://user-images.githubusercontent.com/20383505/148027552-088a9c50-1185-4b5b-858d-9df3c72f57e3.png)

**Comment by Kholid060** [comment]
You can use the click block to click the "@" button
![image](https://user-images.githubusercontent.com/22908993/148637683-38aeba9c-bc88-44b6-b658-d55ab7cdee32.png)

**Comment by whwh656** [comment]
[testgithub.txt](https://github.com/Kholid060/automa/files/7832990/testgithub.txt)
I input '@' in textarea  but it doesn't appear username list ,i can't @anybody how can i use shift + 2 to simulate the event @ to appear username list

**Comment by Kholid060** [comment]
GitHub seems to use [keyboard event](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) to make the username list appear, but I have tried to [dispatch](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) `keyup` and `keydown` event to the form but nothing work. So, the only way I guess is 
using the **Click** block to click the "@" button like what I mentioned in the previous reply.

**Comment by whwh656** [comment]
thanks!the only way I guess is using the Click block to click the "@" button like what I mentioned in the previous reply.
