### ISSUE TITLE
Check SSL Certificate

### ISSUE THREAD

**Issue by AnotherCoolDude** [Kholid060/automa#25]
**Is your feature request related to a problem? Please describe.**
Add the possibility to check if ssl certificate is present and still valid 

**Describe the solution you'd like**
create a block to add to a workflow which checks the ssl certificate of current website

**Describe alternatives you've considered**
use the javascript block. However, checking for ssl with javascript seems to be quite difficult from what google tells me. 

**Additional context**
I know this might not be possible / easy to archive. Maybe we can have the browser tell us about the ssl cert. But I admit, I haven't deep dived into the topic yet.

**Comment by Kholid060** [comment]
I have checked the [chrome extension documentation](https://developer.chrome.com/docs/extensions/reference/), I don't think Chrome has an API to check the SSL certificate. And I'm afraid I can't add this feature into the extension, but if someone has a workaround for this, a PR is welcome.
