### ISSUE TITLE
Как закрыть полностью новое окно

### ISSUE THREAD

**Issue by andizura** [Kholid060/automa#258]
Процесс начинается в новом окне браузера. Нужно, что бы после окончания процесса новое окно полностью закрывалось. Как это сделать? 
![image](https://user-images.githubusercontent.com/72710594/148674157-3b9b6d03-0ad7-4ab6-8fd0-daa7bc5c1cea.png)

PS С вкладками все понятно.

**Comment by Kholid060** [comment]
You can choose the window option in the close tab block. This feature is available in v0.14.1

![image](https://user-images.githubusercontent.com/22908993/148723130-54c967b1-df19-408c-96c0-856667135649.png)

**Comment by andizura** [comment]
> Вы можете выбрать вариант окна в блоке закрытия вкладок. Эта функция доступна в версии 0.14.1.
> 
> ![изображение](https://user-images.githubusercontent.com/22908993/148723130-54c967b1-df19-408c-96c0-856667135649.png)

О, спасибо!)

**Comment by andizura** [comment]
Было бы неплохо, чтобы можно было запускать сценарий по расписанию. Как cron- задачи. Ежедневно в определённые часы. 
![image](https://user-images.githubusercontent.com/72710594/148728221-0398b565-78a7-4bde-808e-cf309fa83a1f.png)
Здесь добавить выбор несколько вариантов часов.
