### ISSUE TITLE
mousemove

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#270]
target url:  https://app.modaiyun.com/damf/rendering-viewer/images/bIBtf3WBIb
![image](https://user-images.githubusercontent.com/20383505/149894440-dc6ed943-4c36-4633-b04d-71aa3b10e565.png)
step1:click the canvas then display  a circle tool
step2: How can i mousermove from -90 degree to 0 degeree

**Comment by Kholid060** [comment]
Use the [trigger event block](https://docs.automa.site/blocks/trigger-event.html) first to trigger the `mousedown` event in the canvas (`.OrbitalImageCanvas-panelExpand`). And for simulating the mouse dragging use the script below
```js
const canvas = document.querySelector('.OrbitalImageCanvas-panelExpand');

for (let index = 1; index < 10; index++) {
  const mouseEvent = new MouseEvent('mousemove', {
    bubbles: true,
    clientX: -(index * 100),
  });
  canvas.dispatchEvent(mouseEvent);
}

automaNextBlock()
```
If you want to rotate to 90 degrees, replace `-(index * 100)` with `index * 100`.
[Dragging.txt](https://github.com/Kholid060/automa/files/7909842/Dragging.txt)
![image](https://user-images.githubusercontent.com/22908993/150453256-3976ad67-18d5-4a92-bb62-7e4810c2297b.png)

**Comment by whwh656** [comment]
Thanks! it works
