### ISSUE TITLE
My workflows no data 

### ISSUE THREAD

**Issue by xiaoxuetong** [Kholid060/automa#274]
**Describe the bug**
![image](https://user-images.githubusercontent.com/34703535/150313607-b18ab5ca-e3ce-4834-8178-4b25407362c0.png)

**To Reproduce**
1. There is no data  
When I first started using it, it worked, but after I tried to publish one, I only displayed the ones that were already published.  Later I want to update it, but can not click, I cancel the post.  To republish, open this menu and don't show any of my local scripts at all.  

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34703535/150314425-737bbd13-391c-4e77-bf2d-332b70ddea28.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by Kholid060** [comment]
Have you updated the extension to the latest version?

**Comment by Kholid060** [comment]
Fixed in v0.16.2
