### ISSUE TITLE
selector

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#276]
target url: https://app.modaiyun.com/damf/rendering-viewer/images/bIBtf3WBIb
![image](https://user-images.githubusercontent.com/20383505/150504339-a0eeb881-0390-4b77-9055-c357e52cbce1.png)
How can  i get the selector icon of share

**Comment by Kholid060** [comment]
You can use the [Element selector](https://docs.automa.site/getting-started/element-selector.html) feature to get the selector of an element. `div:nth-child(4) > .StyledSvg-eYatCs`

![image](https://user-images.githubusercontent.com/22908993/150617786-b61c2111-21f9-49df-8230-08434969aa9e.png)

**Comment by whwh656** [comment]
> You can use the [Element selector](https://docs.automa.site/getting-started/element-selector.html) feature to get the selector of an element. `div:nth-child(4) > .StyledSvg-eYatCs`
> 
> ![image](https://user-images.githubusercontent.com/22908993/150617786-b61c2111-21f9-49df-8230-08434969aa9e.png)

[testqunjingtu.txt](https://github.com/Kholid060/automa/files/7917970/testqunjingtu.txt)
I try it but it doesn't work!
os : mac os

**Comment by whwh656** [comment]
Thanks
