### ISSUE TITLE
New tab block throws an error

### ISSUE THREAD

**Issue by vrnRaptor** [Kholid060/automa#286]
**Describe the bug**
New tab block throws an error in the latest version Automa 0.16.0. It worked in the previous version.

**To Reproduce**
1. Connect new tab block.
2. Add link to the new tab block.
3. Run script.
4. See error.

**Expected behavior**
New tab block execution should not interrupt script execution.

**Additional context**
I use browser Vivaldi 5.0.2497.48.

**Comment by Kholid060** [comment]
Can you take a screenshot of the error?

**Comment by vrnRaptor** [comment]
Sorry i made mistake. Probably a problem with the new tab block.
![2022-01-25 13 06 08 infppggnoaenmfagbfknfkancpbljcca 35cddb037742](https://user-images.githubusercontent.com/13599993/150956182-99c6de4a-2136-44ef-91a0-0d4ce2fe5ad6.png)
![2022-01-25 13 03 17 infppggnoaenmfagbfknfkancpbljcca 50fed2fb26f7](https://user-images.githubusercontent.com/13599993/150955912-6fbf268d-409a-425f-a14f-25800ea1f5ab.png)
