### ISSUE TITLE
[FR] drop block to group not only from left workplace

### ISSUE THREAD

**Issue by evolution-ant** [Kholid060/automa#289]
**Is your feature request related to a problem? Please describe.**
I often create the entire workflow first, then I want to create groups, but I can't drag in the blocks that already exist

**Describe the solution you'd like**
I wish I could drag blocks that are not related to each other

**Additional context**
![2022-01-27-10-22-43-image](https://user-images.githubusercontent.com/24502661/151280723-04fdc9af-015d-4311-80b0-c983c0f64a82.png)

**Comment by Kholid060** [comment]
In version 0.17.0, You can add the existing block to the blocks group by dragging the ![chrome_3gZtyz4CSV](https://user-images.githubusercontent.com/22908993/151649974-978de91d-5cd5-42cf-ae0f-f75a4db2c599.png) button.

![move-block](https://user-images.githubusercontent.com/22908993/151650074-3b445a28-3ef1-49f1-8762-38bb10f0f01b.gif)

**Comment by evolution-ant** [comment]
> Owner

got it , thanks
