### ISSUE TITLE
Documentation Broken link 

### ISSUE THREAD

**Issue by fab10m** [Kholid060/automa#296]
Hi,

the link within the page [Execute Workflow Block](https://docs.automa.site/blocks/execute-workflow.html#global-data) pointing to the page [Global data](https://docs.automa.site/api-reference/global-data.html) is broken because the html extension is missing.

Regards,
Fabio

**Comment by Kholid060** [comment]
Fixed (https://github.com/Kholid060/automa-docs/commit/9119ea66d1f2f8e87712061c77fa05e831ba82cc)
