### ISSUE TITLE
Uncaught Error: Cannot find module './get-pass-key'

### ISSUE THREAD

**Issue by evolution-ant** [Kholid060/automa#301]
**Describe the bug**
Cannot find module './get-pass-key' , get-pass-key.js is ignored , what is this get-pass-key.js , how can i create it.

**To Reproduce**
1. yarn install
2. yarn build

**Screenshots**
![2022-01-29-12-53-10-image](https://user-images.githubusercontent.com/24502661/151647869-aafdbf67-79ac-4a81-9ab0-951fc11edccc.png)

**Desktop (please complete the following information):**
 - OS: Mac Chrome

**Comment by Kholid060** [comment]
You can create a `get-pass-key.js` file inside the `src/utils` folder, and inside of it 

```js
export default function() {
  return 'anything-you-want';
}
```
