### ISSUE TITLE
it alert err when I run js in new tab

### ISSUE THREAD

**Issue by 15718860094** [Kholid060/automa#304]
chorme log show that:

Cannot access contents of url "chrome-extension://infppggnoaenmfagbfknfkancpbljcca/". Extension manifest must request permission to access this host.

**Comment by Kholid060** [comment]
The new tab URL must be included `http://` or `https://` scheme if the URL starts with `chrome://` or `chrome-extension://` the javascript code block won't work.

![image](https://user-images.githubusercontent.com/22908993/151695171-a57d4ef4-8955-44ab-aca5-dfa7c7d7a803.png)
