### ISSUE TITLE
The New Tab is show the tab was closed.

### ISSUE THREAD

**Issue by chanben2005** [Kholid060/automa#306]
I am set the new tab is 'https://www.facebook.com/', but it show the tab was closed.

![image](https://user-images.githubusercontent.com/34121011/151670911-14e2d12d-0055-475f-98b5-67e897689611.png)
![image](https://user-images.githubusercontent.com/34121011/151670952-52a31ffc-955d-463d-be10-0861cd3ab3ad.png)

I don't know this is my problem or bug.

Have a good day!

**Comment by Kholid060** [comment]
What browser are you using?

**Comment by chanben2005** [comment]
I am use cent browser, but for now, it seems that only facebook website is not work.
Oh... I change another brower it can work.

Another question, can I make encrpty or decrpty the global data?  Can I use JavaScript Code to make this idea?

**Comment by Kholid060** [comment]
> Another question, can I make encrpty or decrpty the global data? Can I use JavaScript Code to make this idea?

No, it's not possible to encrypt or decrypt the global data.
