### ISSUE TITLE
How to use "reference data" in Range option?

### ISSUE THREAD

**Issue by hiroki-kd** [Kholid060/automa#308]
<img width="323" alt="Screen Shot 2565-01-30 at 15 42 38" src="https://user-images.githubusercontent.com/49369000/151692922-826ae983-9607-435d-847f-f012f09e53ae.png">

**Comment by Kholid060** [comment]
Currently, it's not possible to use the reference data in the range input but I will add this feature in the next update.

**Comment by hiroki-kd** [comment]
That's great!!, Thank you so much.
