### ISSUE TITLE
Conditions don't work: t.replace is not a function

### ISSUE THREAD

**Issue by nagman** [Kholid060/automa#309]
**Describe the bug**
When I use a conditions block, no matter what I put in it, I'll have this error: `t.replace is not a function`.
Even with an empty condition.

**To Reproduce**
1. Create a Conditions block and leave it empty (or put A == A)
2. Trigger the workflow
3. Look at the logs

**Screenshots**
![image](https://user-images.githubusercontent.com/16116486/151696753-4a53afd3-7b92-4316-bbe3-412fa4d48c8f.png)
![image](https://user-images.githubusercontent.com/16116486/151696758-0885f2f9-7fcb-413d-bc82-99aa4229828e.png)

**Desktop (please complete the following information):**
 - OS: macos 11.6
 - Version: 0.17.2

**Comment by Kholid060** [comment]
Try to remove and add the condition block, if it's still not working try to restart the browser. And can you take a screenshot of the extension version on the about page?

![image](https://user-images.githubusercontent.com/22908993/151698405-4bc62dd4-6805-49e1-b935-8fb4c8ec0f7d.png)

**Comment by nagman** [comment]
Ooooooh... I see the problem.
I thought the workflows editor was a web app linked to an account, and that all was linked to an online platform.
So when I saw a new version was published, I thought "well, if I go on my personal space, it will already have the latest version".
But I had to uninstall the chrome extension and reinstall it (then I found I've lost all my workflows).

Now the conditions block works.

So, every time the extension will be updated, shall we have to dump all of our workflows first, uninstall, reinstall, and reupload our workflows?

**Comment by Kholid060** [comment]
> I thought the workflows editor was a web app linked to an account, and that all was linked to an online platform.
So when I saw a new version was published, I thought "well, if I go on my personal space, it will already have the latest version".
But I had to uninstall the chrome extension and reinstall it (then I found I've lost all my workflows).

No, it's not a web app. All of your workflows are stored in your local machine.

> So, every time the extension will be updated, shall we have to dump all of our workflows first, uninstall, reinstall, and reupload our workflows?

You don't need to dump all of the workflows after updating the extension.
