### ISSUE TITLE
New tab can not be closed opened by the new window block

### ISSUE THREAD

**Issue by signals2** [Kholid060/automa#313]
when the new window block is executing, it will open a new browser window with a default new tab, then the next new tab block will open another new tab, the question is the default tab can not be closed by the 'close tab' block, the url or pattern is 'edge://newtab' or 'edge://*', is it possible to close the default tab or is it possible to reuse the default tab?

**Comment by Kholid060** [comment]
> is it possible to close the default tab

It's possible to close the default tab, to close the default tab use the `edge://newtab/` pattern. And when you write the URL pattern make sure you add a slash (`/`) at the end. For example, `https://example.com` to `https://example.com/`.

> is it possible to reuse the default tab?

It's currently not possible.

**Comment by signals2** [comment]
> > is it possible to close the default tab
> 
> It's possible to close the default tab, to close the default tab use the `edge://newtab/` pattern. And when you write the URL pattern make sure you add a slash (`/`) at the end. For example, `https://example.com` to `https://example.com/`.
> 
Great, it works with 'edge://newtab/'.

> > is it possible to reuse the default tab?
> 
> It's currently not possible.
