### ISSUE TITLE
Element exists block does not work properly on new tab opened by a click element block 

### ISSUE THREAD

**Issue by signals2** [Kholid060/automa#314]
The element exists block works on current active tab, however if the click element block opens a new tab, it seems the element check is still running on the original tab, can i set the new tab as active tab or how can I run the element existing check on the new tab?

**Comment by Kholid060** [comment]
If the click element block clicks an anchor (`<a>`) element, use the [link block](https://docs.automa.site/blocks/link.html) instead.

**Comment by signals2** [comment]
Thanks for your quick reply. 
The clicked element is not an anchor, just an image button. I suggest it's more useful to add a url or pattern option to the element existing block.

**Comment by Kholid060** [comment]
I've been added a Switch tab block where you can switch between tabs using the [match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns), but it'll be available on the next update.

**Comment by signals2** [comment]
hi, when will the switch tab block available for test?
thanks

**Comment by Kholid060** [comment]
It will be shipped in version 1.0.0 which will be released in around 1 week
