### ISSUE TITLE
move black dot 

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#317]
![image](https://user-images.githubusercontent.com/20383505/152674987-c3b60df7-669f-401a-bd33-1f9717986a1c.png)

target url :
https://app.modaiyun.com/share-token/1490253298971942912?source=copylink

I need your help

**Comment by Kholid060** [comment]
You can use the javascript code block to change the slider value
```js
const slider = document.querySelector('.css-krkx2v');
slider.value = '0.3';

automaNextBlock()
```

[testing (4).txt](https://github.com/Kholid060/automa/files/8019881/testing.4.txt)

**Comment by whwh656** [comment]
> You can use the javascript code block to change the slider value
> 
> ```js
> const slider = document.querySelector('.css-krkx2v');
> slider.value = '0.3';
> 
> automaNextBlock()
> ```
> 
> [testing (4).txt](https://github.com/Kholid060/automa/files/8019881/testing.4.txt)
automa's  effect is different from  by manual
when set  slider.value = '1'  by automa , The cube's wall can be seen  (the black dot is  in the end )
![image](https://user-images.githubusercontent.com/20383505/152945634-a65cbd33-8db2-439d-8b2f-3df0369cf453.png)

while i drag this black dot to the end  by manual ，The cube's wall is can't be seen
![image](https://user-images.githubusercontent.com/20383505/152944856-6aff9f92-b69a-4946-9730-e40c14565e9c.png)

![企业微信截图_16443074981263](https://user-images.githubusercontent.com/20383505/152944867-6215f320-3719-48ff-8f42-834ec2454cf5.png)

**Comment by Kholid060** [comment]
Use this script instead

```js
const findReactEvent = (element) => Object.keys(element).find((key) => key.startsWith('__reactEventHandlers'))

const range = document.querySelector('.css-krkx2v');
const reactEvent = range[findReactEvent(range)];

const value = 1;

range.value = value;
reactEvent.value = value;
reactEvent.onChange({ target: range });

automaNextBlock()
```

**Comment by whwh656** [comment]
Thanks！it works
