### ISSUE TITLE
ctrl+a it doesn't work

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#318]
ENV: automa  v17.4    PC: windows10
[TESTBAIDUCTRL+A.txt](https://github.com/Kholid060/automa/files/8013267/TESTBAIDUCTRL%2BA.txt)

I input text :121212, at the same time i want to use  shortcut  CTRL+A  to Select 121212

**Comment by Kholid060** [comment]
The trigger event block only dispatches the event to the element, it does not execute the shortcut. And if you want to select a text, use javascript instead.

```js
// Select input text
const input = document.querySelector('#kw');
input.select();

// Select all text
const range = document.createRange();
range.selectNode(document.body);

const selection = window.getSelection();
selection.removeAllRanges();
selection.addRange(range);
```

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/155493120-23a7352d-e571-4e0f-8408-6b5c79716950.png)
I mean this picture above can represent ctrl+a

**Comment by Kholid060** [comment]
It's currently not possible to that
