### ISSUE TITLE
mouserover support hover css

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#319]

**Comment by Kholid060** [comment]
Duplicate #145 

It's not possible to simulate the CSS hover using javascript

**Comment by whwh656** [comment]
Why selenium can simulate css hover?

**Comment by Kholid060** [comment]
As far as I know, it's because selenium has access to the native browser API.

**Comment by whwh656** [comment]
> As far as I know, it's because selenium has access to the native browser API.


<img width="342" alt="image" src="https://user-images.githubusercontent.com/20383505/153737828-24d77a4d-ca06-4c5f-b49a-9912e0fa72e4.png">

https://endtest.io/
I found this website which can simulate hover
