### ISSUE TITLE
How can I use the data by saved some element's attribute value

### ISSUE THREAD

**Issue by lynnk1ng37** [Kholid060/automa#32]
**Is your feature request related to a problem? Please describe.**
before I Form an value, I have saved some element's attribute as a Data Column, Then how can I use this saved attribute value for the next step?

**Describe the solution you'd like**
pls tell me if it supports

**Comment by Kholid060** [comment]
You can write `[data@path]` to insert the data of data columns on the next block. And on the `path` part, you need to write the path of the data for example `[data@0.columnName]` to get the first data of the `columnName` column, `[data@1.columnName]` for the second data, and so on. And this is only working on the new tab and the forms block.

**Comment by lynnk1ng37** [comment]
thanks for replying me, but as I use this [data@path], it doesn't work anyway.
I first use Attribte value to save data columnName as hid_answer, and second Forms text and the path is [data@0.hid_answer],
then when I run this task, it doesn't parse this dataPath.
would you pls tell me where wrong am I? pls have a look at this screenshot.
![case1](https://user-images.githubusercontent.com/60334442/141036831-ff7665a7-5466-4fc6-822e-5f285e15efd5.png)

**Comment by Kholid060** [comment]
Are you using the latest version of the extension? The latest version is 0.3.1

**Comment by lynnk1ng37** [comment]
yes, I am using Version 0.3.1.
May you write a demo to validate it work well?

**Comment by Kholid060** [comment]
You can try this example [Attribute.txt](https://github.com/Kholid060/automa/files/7510283/Attribute.txt) (convert it to JSON first and then import it).

**Comment by lynnk1ng37** [comment]
yeah, I solved this issue, because I wrote a wrong attribute name not "value".
thank you very much!

**Comment by cereschen** [comment]
0.4.7,It doesn't work

**Comment by Kholid060** [comment]
@cereschen if you're using `[]`, in the newer version replace it with `{{}}`. 
`[data@1.columnName]` => `{{data@1.columnName}}`

**Comment by amgmbs** [comment]
> You can try this example [Attribute.txt](https://github.com/Kholid060/automa/files/7510283/Attribute.txt) (convert it to JSON first and then import it).

Hello and congratulations for this great app!

I've imported attribute.json but yesterday with 0.10 and today with 0.11
but on google search it sets the value

{{data@0.testing}}
and not 
Google Search
