### ISSUE TITLE
How to continue when an alert occurs?

### ISSUE THREAD

**Issue by Ne0Page** [Kholid060/automa#325]
It stops when the website sends an alert window .

**Comment by Kholid060** [comment]
Use the javascript code block and input the below script to temporarily prevent the website from showing up an alert

```js
const alertWindow = window.alert;
window.alert = () => {
  window.alert = alertWindow;
}

automaNextBlock();
```

![image](https://user-images.githubusercontent.com/22908993/153566840-bf8edfc8-1008-4f73-a2ac-46202c7acf82.png)
