### ISSUE TITLE
how to dynamic access a row in a dataColumn

### ISSUE THREAD

**Issue by Deneb77** [Kholid060/automa#326]
Hello

Using javascript node i create a table in a loop

```
let v_href = document.querySelector("a[href*='previewFmFile']").href;
automaNextBlock({href:v_href});
```

at each loop my array grow like [{href:'url1'},{href:'url2'} ... ] 

then next in the loop in an upload component i want to use the url:

{{ dataColumns@0.href }}

how to replace the 0 by the current loop index

I have tried :
{{dataColumns@loopData@iwbcm3.$index.href}}
{{dataColumns@(loopData@iwbcm3.$index).href}}
{{dataColumns@{{loopData@iwbcm3.$index}}.href}}

nothing work
thx

**Comment by Deneb77** [comment]
thx

**Comment by JimmyBastos** [comment]
I'm trying to do the same, no success. Do you have any suggestion to write/access data inside the loop?

**Comment by Kholid060** [comment]
In v1.0.0 you can do `{{dataColumns@[loopData@iwbcm3.$index].href}}`
