### ISSUE TITLE
How to loop the Numbers

### ISSUE THREAD

**Issue by wanyx2015** [Kholid060/automa#327]
Hi, I have problem looping the Numbers.

Below is my setup:

![image](https://user-images.githubusercontent.com/15007925/153568897-1580c112-8b12-4fb9-a32c-5679f602c14b.png)

And here is how I access the loopId

![image](https://user-images.githubusercontent.com/15007925/153569044-820a9941-a1e8-46ec-808f-fa52be2a8ee6.png)

But it does not loop as expected and instead it reports follows:

![image](https://user-images.githubusercontent.com/15007925/153569217-2401ef74-4e07-4bba-856b-2a86da35931a.png)

What is the right way to access the Numbers in loop?

Thanks

**Comment by Kholid060** [comment]
You can access it by `{{ loopData@num }}`, but I think there's a bug with the extension in which it returns the wrong value.

**Comment by wanyx2015** [comment]
Thanks for the update, could you let me know when I can get a new release?

**Comment by Kholid060** [comment]
What do you mean?
