### ISSUE TITLE
How to retrieve a small array

### ISSUE THREAD

**Issue by Radanca** [Kholid060/automa#345]
I have 3 portfolios on Yahoo Finance. How to retrieve the name of each portfolio and their value.
Do I need to use a Loop Data block or Repeat Task block ? 
![Yahoo Finance](https://user-images.githubusercontent.com/74746419/153928730-ecd54600-33db-4820-82c7-7c1926fd616f.png)

I'd like to export the 6 data to a CSV file.
![Yahoo Finance2](https://user-images.githubusercontent.com/74746419/153929356-4609f423-2400-449a-b4b5-a33f851c02cb.png)

And how to overwrite the csv file each day ?
Thanks.

**Comment by Kholid060** [comment]
You can use one get text block to retrieve all the portfolios by checking the `Multiple` checkbox, but the element selector must be matched with all the portfolios elements.
![image](https://user-images.githubusercontent.com/22908993/154063658-53dea901-8155-4011-ba4a-8363ea21319a.png)

**Comment by Radanca** [comment]
Can I find a Workflow example to export a table/array to a csv file ?

**Comment by Kholid060** [comment]
You can use the workflow below as the example
[Portfolio.txt](https://github.com/Kholid060/automa/files/8078564/Portfolio.txt)

Change the file extension from `.txt` to `.json` first and then import it into Automa

**Comment by Radanca** [comment]
Great, that works !
How to overwrite the CSV file ? I want to keep the same file name, the workflow will run on interval.
A Excel file will retrieve the csv file data.
Thanks again.

**Comment by Kholid060** [comment]
It's not possible to overwrite a file because Automa doesn't have access to the files on your computer.

**Comment by Radanca** [comment]
Thanks Kholid for your help.
I'm going to script the file removing.
