### ISSUE TITLE
Support The Element Disappear Block

### ISSUE THREAD

**Issue by xiezhuangping** [Kholid060/automa#346]
The project is very cool!

There is an Element Exists Block. Can we support the Element Disappear Block to wait loading finished?

**Comment by Kholid060** [comment]
You actually can use the element exist block to do that, for example

![image](https://user-images.githubusercontent.com/22908993/154065405-5cff2606-9734-4284-b7d4-a7c6040bd45f.png)

If the `.is-loading` exists in the DOM the workflow will execute the delay block and then try to check the element again, and when the `.is-loading` doesn't exist the workflow will execute the new tab block.

**Comment by xiezhuangping** [comment]
Here is my solution (with timeout):
![image](https://user-images.githubusercontent.com/7053995/154432078-ddf48dea-cee5-463d-b9f5-e07702dac46e.png)

It's not very clear imo. so i commit the issue.


> You actually can use the element exist block to do that, for example
> 
> ![image](https://user-images.githubusercontent.com/22908993/154065405-5cff2606-9734-4284-b7d4-a7c6040bd45f.png)
> 
> If the `.is-loading` exists in the DOM the workflow will execute the delay block and then try to check the element again, and when the `.is-loading` doesn't exist the workflow will execute the new tab block.
