### ISSUE TITLE
How to set the workflow to be automatically triggered at a specific time each day?

### ISSUE THREAD

**Issue by lartpang** [Kholid060/automa#35]
**Is your feature request related to a problem? Please describe.**
How to set the workflow to be automatically triggered at a specific time each day? 

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/26847524/140873875-befad681-3da5-4444-bc67-cf48cc11692b.png)

I want to try to use the "interval" option to set. But the unit of time can only be "minute".

**Describe alternatives you've considered**

Perhaps this great extension can provide more flexible unit selection and time settings.

**Additional context**

None.

**Comment by Kholid060** [comment]
Current automa doesn't have that kind of ability, I'll add this feature in the future.

**Comment by lartpang** [comment]
@Kholid060 Thanks!

**Comment by lynnk1ng37** [comment]
Hi, lartpang, why I can not find this option "interval"? May you tell me where is it?
![image](https://user-images.githubusercontent.com/60334442/141074589-addc6efd-68e7-40dd-9cc9-103d8361f3b1.png)

**Comment by Kholid060** [comment]
Click the edit button at the trigger block
