### ISSUE TITLE
Can automa support zoom in and zoom out?

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#353]

**Comment by Kholid060** [comment]
Do you mean zoom in and zoom out like this?

![123a](https://user-images.githubusercontent.com/22908993/154268514-0656fb7a-f203-467b-952b-0840e710bebf.gif)

**Comment by whwh656** [comment]
Scroll forward in the middle of the mouse to zoom in
Scroll backward in the middle of the mouse to zoom out

**Comment by Kholid060** [comment]
> Scroll forward in the middle key of the mouse to zoom in
> Scroll backward in the middle key of the mouse to zoom out

I think it's doing the same thing.

Or can you explain more about in which context this zoom in and out is happening, does it zoom in and out the tab like my previous reply or something else?

**Comment by whwh656** [comment]
yes

**Comment by whwh656** [comment]
I find the  wheel event in the block of trigger event that it have the same effect
