### ISSUE TITLE
go back block

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#378]
https://github.com/Kholid060/automa-docs/issues/4
automa v 1.0.2
1 open url1
2 update  url1  as  be  url2
3 we use the block of go back but  i find that the tab's url is still  url2

**Comment by Kholid060** [comment]
It's not working because the tab doesn't have history to go back into

![chrome_RKjf63ZuM0](https://user-images.githubusercontent.com/22908993/155669114-3faaba2a-611b-450e-98b0-b782a164bfeb.png)

**Comment by whwh656** [comment]
why?

**Comment by Kholid060** [comment]
I don't really know, but I think it might be a bug or it's the chrome behavior to not save the history if the tab is updated.
