### ISSUE TITLE
Trigger an Action from a Website with CustomEvent and/or general Events

### ISSUE THREAD

**Issue by ZlydeTJ** [Kholid060/automa#382]
**Is your feature request related to a problem? Please describe.**
I want to use the automation from my own website to automate certain actions after I'm done using the website. So e.g.: It would be nice to start a search to an internal tool directly from my website when clicking a button with the related keyword, instead of copying it and then starting my actions. Especially since I have a lot of actions available. I currently have a Chrome-Plugin that does exactly this, however it would be more convenient to also use automa for this tasks.

**Describe the solution you'd like**
In my plugin I use the chrome api `chrome.runtime.onMessage.addListener` to listen for events which I throw through the `new CustomEvent`(I think the plugin does already this with a different kind of website/plugin interaction). It would be nice to have an Event like this:

```javascript
new CustomEvent('automa-start-workflow', {
  detail: {
    id: 'nbf6-qlwD-JCVptpnf9EF', // workflow id
    // custom data I want to pass to the workflow
    // maybe pass this as a variable? Or into the global data
    data: {
      keyword: 'Example Keyword'
    }
  }
}))
```

Which would start the workflow based on the id. I'm not sure what the best way would be to pass the data (maybe variable or global data). 

Would this fit?

Alternatively what also would work is listening to all Button Browser events and have a certain trigger. For example if I were to post a comment on a website I would like to paste that comment also into a Google Docs Table. I could listen whenever a certain button is pressed a trigger a workflow. 

This use-case is a bit broader since it also covers site that the workflow creator possible has no control over, however it would be a bit harder to pass data along, as this would first has to be scraped.

**Comment by Kholid060** [comment]
That's a good idea.

> In my plugin I use the chrome api `chrome.runtime.onMessage.addListener` to listen for events which I throw through the `new CustomEvent`(I think the plugin does already this with a different kind of website/plugin interaction). It would be nice to have an Event like this:
> 
> ```js
> new CustomEvent('automa-start-workflow', {
>   detail: {
>     id: 'nbf6-qlwD-JCVptpnf9EF', // workflow id
>     // custom data I want to pass to the workflow
>     // maybe pass this as a variable? Or into the global data
>     data: {
>       keyword: 'Example Keyword'
>     }
>   }
> }))
> ```
> 
> Which would start the workflow based on the id. I'm not sure what the best way would be to pass the data (maybe variable or global data).

To pass data to the global data or variable of the workflow, I guess the best way is by using the `variables` or `globalData` property inside the `data` object.

```js
new CustomEvent('automa-start-workflow', {
  detail: {
    id: 'nbf6-qlwD-JCVptpnf9EF',
    data: {
      globalData: 'Example keyword' // Pass it to the workflow global data
      variables: {
        variableName: 'Example to keyword'
      } // Pass it to the workflow variables
    }
  }
}))
```

**Comment by ZlydeTJ** [comment]
@Kholid060 Wow it's already implemented that was quick! Thank you very much :) 

I have yet to test it, but I think we can close this issue now.

**Comment by Kholid060** [comment]
> @Kholid060 Wow it's already implemented that was quick! Thank you very much :)
> 
> I have yet to test it, but I think we can close this issue now.

You're welcome, but to start to execute a workflow use the `automa:execute-workflow` event. E.g. `new CustomEvent('automa:execute-workflow', {})`

**Comment by ZlydeTJ** [comment]
Thank you for the reminder. Once I've tested it through I let you know if there are any issues :)

**Comment by ZlydeTJ** [comment]
Hi @ whwh656,

sorry its for private use only. But I can share my workflow in the public library later, if that helps.

**Comment by whwh656** [comment]
> Hi @ whwh656,
> 
> sorry its for private use only. But I can share my workflow in the public library later, if that helps.

Thank you, your share  is appappreciate

**Comment by ZlydeTJ** [comment]
Hey @whwh656,

I build a small example here: https://www.automa.site/workflow/4Qjh_xUtW7Ow5WdB1YrF6

I've put the instruction on how to do use it in the description.

**Comment by ZlydeTJ** [comment]
It's really simple actually.

 You just select the workflow you want the ID from:
![select-workflow](https://user-images.githubusercontent.com/60395639/156365219-5c07ea1d-d88f-4045-a43d-600254a237c8.png)
Now you can select the ID from the URL:
<img width="960" alt="copy-id-from-url" src="https://user-images.githubusercontent.com/60395639/156365229-8fd48de7-f802-464e-8119-530ffc4d8654.png">

**Comment by whwh656** [comment]
thanks

**Comment by whwh656** [comment]
version 1.2.1
exectute workflow  have the same funcition of above
i 'm confused why write javascript code by the new CustomEvent in jsblock  by myself
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/20383505/156471265-5962718d-7bd7-43d8-9580-3115a10446c8.png">

**Comment by whwh656** [comment]
> I've put the instruction on how to do use it in the description.

I want to know the active tab

> Hey @whwh656,
> 
> I build a small example here: https://www.automa.site/workflow/4Qjh_xUtW7Ow5WdB1YrF6
> 
> I've put the instruction on how to do use it in the description.

 I want to know that  the funciton of  active tab block ? l am looking  forwart to your reply

**Comment by ZlydeTJ** [comment]
Hey @whwh656,

you would need it if you want to trigger a Workflow from any other source than the plugin itself. Usually you start a Workflow by clicking on it, or visiting a website or at a certain time or a keyboard shortcut. 

However In my App I need to trigger a Workflow from my own Website via a Button. This button does things for my own website, however I want to execute a workflow directly after this, without triggering it via any other method. Also this allows me to pass data to the Workflow from my app.

**Comment by quoskin011** [comment]
Can you help me make a video tutorial?
