### ISSUE TITLE
Allow Mustache Syntax in Switch Tab Pattern

### ISSUE THREAD

**Issue by ZlydeTJ** [Kholid060/automa#387]
**Is your feature request related to a problem? Please describe.**
In my Workflow I open an a website and scroll through the comments and open some of the profiles in a new tab. To switch back to the original tab I save the url where I was working on in a variable. I wanted to use this url with `{{variables.workingTab}}` as "Match Patterns", however when executing the workflow I get an error: 
> Invalid url pattern '{{variables.workingTab}}'

Which is a correct error.

**Describe the solution you'd like**
Replace the mustache with the variable contents. As an addition we could also expand the error message if we used a variable, to allow for better debugging (if that is possible).

**Describe alternatives you've considered**
A Block which just switches to the previous tab I used before I opened a bunch of tabs? This sound complicated though, so replacing mustache would be the easiest.

**Additional context**
Workflow Snippet.
In 1 I set the variable `automaSetVariable('workingTab', window.location.href);`

In 2 I use the variable `{{variables.workingTab}}`
<img width="1032" alt="workflow-snippet" src="https://user-images.githubusercontent.com/60395639/156358210-01d66a7f-acdc-4cb6-babe-fdc21643f265.png">

**Comment by Kholid060** [comment]
> In my Workflow I open an a website and scroll through the comments and open some of the profiles in a new tab. To switch back to the original tab I save the url where I was working on in a variable. I wanted to use this url with `{{variables.workingTab}}` as "Match Patterns", however when executing the workflow I get an error:
> 
> > Invalid url pattern '{{variables.workingTab}}'

You need to replace the first dot with the `@` symbol, for example `{{ variables@workingTab }}`.

**Comment by ZlydeTJ** [comment]
Ohhh, whoopsie, thanks for mentioning it!
