### ISSUE TITLE
execute workflow call other workflow

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#388]
1 workflow1 : trigger event manual
2 workflow2: trigger event by special date  for example:  date in the future 2022-03-07
3  we call workflow2  in workflow1   I find workflow2 is also work ,  but i think the workflow2's  trigger  don't work  because the trigger date is the future

**Comment by Kholid060** [comment]
So, you are trying to trigger workflow2 in workflow1 but when you execute workflow1, workflow2 doesn't get triggered?

Or can you explain more what the problem is?

**Comment by whwh656** [comment]
sorry i don't describe my question clearly.
I mean when workflow1 call workflow2
whether workflow 1 check workflow2's triggle event?

**Comment by Kholid060** [comment]
> whether workflow 1 check workflow2's trigger event?

No, the workflow2 will be get called immediately
