### ISSUE TITLE
Can automa support switch iframe and window?

### ISSUE THREAD

**Issue by Kholid060** [Kholid060/automa#39]
### Discussed in https://github.com/Kholid060/automa/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **moveurbody** November  9, 2021</sup>
I try to locate a button element in an iframe, but I can't use the element selector to locate the button element.
In selenium, it provides switch iframe and detects window. I think if you can support these functions will be awesome.</div>

**Comment by SARDONYX-sard** [comment]
This URI might be helpful to you. :)

https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow
