### ISSUE TITLE
Start Workflow loopdata from the last index of previous Workflow launch

### ISSUE THREAD

**Issue by JeremLopes** [Kholid060/automa#392]
Hi Ahmad,

There is a way to start a Workflow loopdata from the last index of previous launch ?
For example, I'm going through a Google spreadsheet with lots of rows that I'm updating as I go. When the workflow stops due to an error or other, I have to restart from the beginning by overwriting the previous data, which wastes a lot of my time. It would be very useful to have a system that allows you to start from where you left off the time before.

Thank you in advance and have a nice day !

**Comment by ZlydeTJ** [comment]
This would be super handy, I'm currently facing the same issue. I want to make some of my scripts run over long period of time (> 8 hours) and I'm not sure how I would implement a restart where I left of if something goes wrong.

**Comment by Kholid060** [comment]
> There is a way to start a Workflow loopdata from the last index of previous launch ?

Currently, there's no way to do that, but I might add this feature on the next update.

**Comment by JeremLopes** [comment]
Thank you very much, this will be very useful to me !

**Comment by Kholid060** [comment]
Maybe I can add a "Reuse last workflow state" option in the workflow settings which will use the last workflow state like the data on the table, variables, etc.

**Comment by JeremLopes** [comment]
Hi @Kholid060,
I have come to hear your news about this new feature "Reuse last workflow state", you plan to release it in the next version ?
Thank you again and have a nice day ! :)

**Comment by Kholid060** [comment]
Hi @JeremLopes,

It will be released in v1.5.0
