### ISSUE TITLE
Reference globalData is not working

### ISSUE THREAD

**Issue by stee-ift** [Kholid060/automa#396]
**Describe the bug**
1. In javascript code, calling automaRefData('globalData') returns an object rather than the one we defined in Global Data.
2. Same thing happens when trying to use mustache tag to reference global data.

**To Reproduce**
Import the attached workflow and see the output in console.

**Expected behavior**
automaRefData('globalData') should return the content we defined in Global Data. (As I recall, it used to return a string that I have to use eval(automaRefData('globalData')) to convert it to object or array)

**Screenshots**
The object that automaRefData('globalData') returns:
![image](https://user-images.githubusercontent.com/90451454/157800068-77c3ecce-98b8-4322-9784-5d472bbbb31b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 99
 - Extension Version: v1.4.0

**Additional context**
This is a great project and I love it!!
[Test.json.txt](https://github.com/Kholid060/automa/files/8228948/Test.json.txt)

**Comment by Kholid060** [comment]
Sorry for the inconvenience, I forget to assign the global data to the workflow engine. I'll fix this bug as soon as possible.
