### ISSUE TITLE
Help me please, I want to build but I get an error

### ISSUE THREAD

**Issue by sacly** [Kholid060/automa#398]
ERROR in ./src/utils/decrypt-flow.js 6:0-40
Module not found: Error: Can't resolve './get-pass-key' in 'F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils'
resolve './get-pass-key' in 'F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils'
  using description file: F:\Programming\Javascript\Practice\automa-main\automa-main\package.json (relative path: ./src/utils)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: F:\Programming\Javascript\Practice\automa-main\automa-main\package.json (relative path: ./src/utils/get-pass-key)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key doesn't exist    
      .jpg
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.jpg doesn't exist      .jpeg
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.jpeg doesn't exist
      .png
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.png doesn't exist      .gif
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.gif doesn't exist      .eot
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.eot doesn't exist      .otf
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.otf doesn't exist      .svg
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.svg doesn't exist      .ttf
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.ttf doesn't exist      .woff
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.woff doesn't exist
      .woff2
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.woff2 doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.js doesn't exist 
      .vue
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.vue doesn't exist      .css
        Field 'browser' doesn't contain a valid alias configuration
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.css doesn't exist      as directory
        F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key doesn't exist    
 @ ./src/background/index.js 11:0-68 71:21-36 72:32-43

webpack 5.70.0 compiled with 1 error in 37198 ms
i ｢wdm｣: Failed to compile.

**Comment by whwh656** [comment]
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/20383505/158063972-c265ee04-debe-4d2b-82a7-83f90cdbdcbc.png">
you can solve the problem by create null of secrets.development.js in root project folder
(the file of secrets.development.js  have no nothing text in it )

**Comment by whwh656** [comment]
\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.jpeg
-----------------------------------------------
The error 2 :you can create null get-pass-key.jpeg in path above by yourself

The error 3:
F:\Programming\Javascript\Practice\automa-main\automa-main\src\utils\get-pass-key.vue doesn't exist .css
------------------------------------------
you can create null get-pass-key.vue in path above by yourself

**Comment by whwh656** [comment]
So,you only create three file by yourself in project folder

**Comment by sacly** [comment]
I found the solution in Discord. It works for me
![image](https://user-images.githubusercontent.com/10547698/158067754-6c362940-3cbe-4b32-a4c9-5dd454e45c07.png)
