### ISSUE TITLE
Can't access css path of modal

### ISSUE THREAD

**Issue by 1Mark** [Kholid060/automa#399]
**Describe the bug**
Can't access css path of modal to select it via automa

**To Reproduce**
1. Go to any youtube video
2. Click on three dot next to a comment
3. Select Report
4. automa cannot choose an element from this list since it just detects it as [focused]

**Expected behavior**
You can choose any radio button from the list

**Screenshots**
![image](https://user-images.githubusercontent.com/15360245/158065176-2c38e325-22ad-429a-912e-451f73e571c2.png)
**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Google Chrome
 - Extension Version: 4.1.2

**Additional context**

**Comment by Kholid060** [comment]
Fixed in v1.4.4
