### ISSUE TITLE
Rename downloaded file before saving it

### ISSUE THREAD

**Issue by Anat0m** [Kholid060/automa#401]
Hi,

Is it possible to rename the file before downloading/saving it? 

My use case would be:
Go to some website that has links that can be clicked and it opens the save file menu where I can set location and file name (usual windows stuff). Would it be possible to obtain the file name that is currently being saved and change it to my preference?

**Comment by Kholid060** [comment]
Currently it's not possible to do that, but I will add this feature on the future update

**Comment by Anat0m** [comment]
Maybe there is timeline for future features?
