### ISSUE TITLE
the block of handle dowload it doesn't works

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#405]
automa v1.5.0
it don't rename my download 
[testdowmload.txt](https://github.com/Kholid060/automa/files/8309173/testdowmload.txt)
file

**Comment by Kholid060** [comment]
It worked when I try it

![download](https://user-images.githubusercontent.com/22908993/159162454-ba4642c0-4d8d-47ec-b254-086fdf030d59.gif)

**Comment by whwh656** [comment]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/20383505/159195049-effce9c4-c222-4878-b233-2db3acdcba80.png">
<img width="891" alt="image" src="https://user-images.githubusercontent.com/20383505/159195081-3e1a5403-ede6-44d7-8b0d-64281e3be96e.png">
I have installed
two plugin automa1.5.0 and download overwrite exist file,but they have same effect ,
automa is conflict  with another plugin: download overwrite exist file
