### ISSUE TITLE
new tab doesnt open file:// links

### ISSUE THREAD

**Issue by hribik100** [Kholid060/automa#406]
so i have a open tab with a file:// link and it erros out. i tried it on windows and raspbian linux in chrome and chromium

**Comment by Kholid060** [comment]
You can't open a new tab with the `file://` scheme, the new tab must start with `http://` or `https://`

![image](https://user-images.githubusercontent.com/22908993/159162715-2e8bc08c-d4ae-420d-a3a0-6d28ddab9a32.png)

Read more on the [chrome developers page](https://developer.chrome.com/docs/extensions/reference/tabs/#method-create)

**Comment by hribik100** [comment]
yes but file can be a webpage and is a normal scheme then why it isnt allowed ?

**Comment by hribik100** [comment]
oh okay
