### ISSUE TITLE
Image Quality Settings get Ignored

### ISSUE THREAD

**Issue by ZlydeTJ** [Kholid060/automa#408]
**Describe the bug**

**To Reproduce**

1. Go to any visual complex site. [Example](https://www.google.com/search?q=water&tbm=isch)
2. Take a screenshot with 100% quality
3. Take a screenshot with 10% quality
4. Compare Sizes (Both are around 1.7 MB)

**Expected behavior**
One of the screenshot should be significant lower quality. Either visually or in file size (perfect would be both).

**Screenshots**
Low Quality (1.7 MB)
![screenshot_low_quality](https://user-images.githubusercontent.com/60395639/159226131-6ad95b35-f1f6-4f06-b57a-b0ff271dfd4a.png)

Hight Quality (1.7 MB)
![screenshot_hight_quality](https://user-images.githubusercontent.com/60395639/159226147-39117635-7c0d-4dbd-83be-875f224bdb32.png)

**Desktop (please complete the following information):**
 - OS: macOs Montery v12.1
 - Browser: Google Chrome v99
 - Extension Version: 1.5.0

**Additional context**
[Script to reproduce error](https://automa.site/workflow/gyIkSQTVp3zBUU1ZHl3K0)

**Comment by Kholid060** [comment]
The quality settings only work if the image type is `jpeg`.

High quality (876 KB)
![screenshot_hight_quality](https://user-images.githubusercontent.com/22908993/159237185-a25dd483-1c2d-44eb-8854-b5c9daffdf93.jpeg)

Low quality (484 KB)
![screenshot_low_quality](https://user-images.githubusercontent.com/22908993/159237193-721ffdd9-4ad1-485b-a259-8f4f864660dd.jpeg)

**Comment by ZlydeTJ** [comment]
Makes sense! I overlooked that you can change the image type.
