### ISSUE TITLE
Add tabs to group

### ISSUE THREAD

**Issue by tomshaw650** [Kholid060/automa#41]
I'm using your amazing app to open up a big set of tabs that I want to use as a workflow.

In Chrome at least, we have the option to add multiple tabs to a group. I would like the ability to add to group with Automa

The only alternative now is a lengthy set of rules to click on each tab and add to group over and over, which I think could be better suited to a single command in Automa.

Potentially, the command could be added, and could have mutliple parameters which would be the tabs open currently. So the user could choose which tabs and how many to be added to the grouping. Also, Chrome allows us to add a group name. Maybe another parameter could be to add the group name automatically too?

**Comment by Kholid060** [comment]
Maybe I'll add a tab groups block where you can edit all the parameters that you mentioned, and add a selection to the new tab block so you can select whether the new tab should be in a group or not.

**Comment by tomshaw650** [comment]
Thats a great implementation for the idea, thanks for the reply and thank you for the amazing extension!
