### ISSUE TITLE
Mouse movement causes interface to disappear

### ISSUE THREAD

**Issue by GatherStar** [Kholid060/automa#413]
**Describe the bug**
In the renaming interface, after the mouse selects the text and moves outside the interface, the interface will disappear abnormally.

**Screenshots**
![22222212](https://user-images.githubusercontent.com/50571479/160071725-14b9d2e8-17eb-4e96-878f-de955ab33ec4.gif)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: [Google Chrome 99.0.4844.82  （64  ） (cohort: Stable) ]
 - Extension Version: [1.5.1]

**Comment by Kholid060** [comment]
It's expected behavior when you release the mouse in the overlay area the modal is close.
