### ISSUE TITLE
Unable to join two blocks

### ISSUE THREAD

**Issue by bawatrader** [Kholid060/automa#42]
**Describe the bug**
Initially when I had installed the extension I was able to join two blocks and i was able to execute the automation also. After sometime I tried to do condition coding and after that I am unable to join two blocks. I tried re-installing the extension but still no luck.

But If I export earlier created workflow then it is working. No luck new workflow creation part.

**Screenshots**
This is the snapshot where i tried to join two block. Image clearly shows i tried to connect two blocks (i took snapshot without release mouse click, hence it can be seen as joining)
![image](https://user-images.githubusercontent.com/74675840/140975400-931d8848-6119-40d3-ab23-9cdb900279ec.png)

As soon as i release the mouse click, line joining two block vanished. Snap for same is below
![image](https://user-images.githubusercontent.com/74675840/140975668-271c600f-62a4-49af-8b21-36ba6f031bc9.png)

 - OS : Windows 10

**Comment by Kholid060** [comment]
Can you take a screenshot of the console tab in the devtool after you try to connect the block?

**Comment by bawatrader** [comment]
yes...let me capture it..nothing updates on console

Before joining blocks
![image](https://user-images.githubusercontent.com/74675840/141064309-f24968bf-12df-4a9e-b9e2-3d838aef1454.png)

Console snap after after joining block
![image](https://user-images.githubusercontent.com/74675840/141085289-2a887ed3-e1fb-469d-b73a-9e824b59127c.png)

**Comment by installtech** [comment]
Hello
I was facing same issue. I think it's related to screen resolution as I reproduce it only on my laptop screen and not on my external screen.

=> You just have to release mouse click at the black dot, even is the line is a little bit above.

![image](https://user-images.githubusercontent.com/1864465/141097584-d2f566c5-3331-41f1-a539-d5c46b1edae8.png)


By the way, thank you for your work and sharing @Kholid060  :)

**Comment by bawatrader** [comment]
Thanks @installtech 

It is amazing extension. We are planning to utilize it for daily basis. Thank you for sharing this product with us @Kholid060 

Let me try to try with diff resolution. Will update the finding over here

btw, this is my first time updating on github. I am on github because of this product.

**Comment by bawatrader** [comment]
@installtech You are great.

I tried changing the resolution and it worked 

![image](https://user-images.githubusercontent.com/74675840/141154145-41f4e0bc-c71b-4582-b19a-4b26ec463900.png)

Marking ticket as closed.
