### ISSUE TITLE
switchtab

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#430]
If i open the same url  three time in chrome tab once a time ,how can i use block switchtab every tab as the funcition we press key :ctrl+tab

**Comment by Kholid060** [comment]
You can add a query in the new tab URL to differentiate each of the tabs, for example in the first tab `https://example.com?tabId=1`, in the second tab `https://example.com?tabId=2`, and so on. And in the switch tab block, you can input `https://example.com?tabId=1` or `https://example.com?tabId=2`. You can import the below workflow as an example

[loop (3).txt](https://github.com/Kholid060/automa/files/8407016/loop.3.txt)

**Comment by whwh656** [comment]
good job! it works.
