### ISSUE TITLE
Trigger on a specific day does NOT start

### ISSUE THREAD

**Issue by Radanca** [Kholid060/automa#432]
the workflow starts once and never more.
The Chrome tab does not open on the web site configured in the workflow.

![Automa](https://user-images.githubusercontent.com/74746419/161636949-a0d64d1c-ea03-4dcd-bc84-73c6f988fe4e.png)

**Comment by Kholid060** [comment]
Which version of Automa are you using?

**Comment by Radanca** [comment]
1.6.6

**Comment by Kholid060** [comment]
Try to re-add the time, because the "on a specific day" trigger is working fine when I tested it.

**Comment by milestone-git** [comment]
I have the same issue here
Sometimes it worked sometimes it didn't

**Comment by fosple** [comment]
Do you have Chrome open and running?

**Comment by Radanca** [comment]
Yes, Chrome is opened. It looks like the issue is fixed with the version 1.6.6.
Today it has worked.

**Comment by milestone-git** [comment]
Yes, Chrome is opened. It looks like the issue is fixed with the version 1.6.6.
Today it has worked.
Me too.
