### ISSUE TITLE
support webapp test : enterkey  event 

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#434]
1 loginurl:
https://accounts.ctrip.com/H5Login/login_ctrip?innerbackurl=index%3Finnerbackurl%3DT
account:15507739847
password:xxxddee
2
<img width="782" alt="image" src="https://user-images.githubusercontent.com/20383505/162207610-288bffb7-6d17-4c06-a8e8-b51efb3af63f.png">

3
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/20383505/162208036-08b3631f-e6fe-4382-96c9-5f096f36f25c.png">
4
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/20383505/162208862-a8ad0409-a038-4533-88ff-90c9f7db434c.png">

**Comment by Kholid060** [comment]
Try use the [trigger event](https://docs.automa.site/blocks/trigger-event.html) block with this options
![image](https://user-images.githubusercontent.com/22908993/162548235-6c5160c3-a88f-4562-905b-c0a65d1a9392.png)

**Comment by whwh656** [comment]
great! thanks
