### ISSUE TITLE
Make editor more visually clear and modeling easier 

### ISSUE THREAD

**Issue by fosple** [Kholid060/automa#435]
First of all: Thanks for developing this awesome tool. It already has saved me sooo much time! Thanks a lot 💪🙂

**Is your feature request related to a problem? Please describe.**
More complex workflows become visually unclear in the current editor and complicated to model: E.g. no selection tool in the editor to move blocks around, insert blocks in a already existing process is hard (you manually have to move all blocks before and after the inserted block around to make it fit), connections between blocks are overlapping in bigger workflows,...

**Describe the solution you'd like**
bpmn-js is really the gold standard when it comes to modeling BPMN processes. They make sure you have a clean layout in the end. Maybe you could get some inspiration from them or even use parts of their code: 

- Website: https://bpmn.io/toolkit/bpmn-js/
- Github: https://github.com/bpmn-io/bpmn-js
- Demo (try it out): https://demo.bpmn.io/new

**Additional context**
More complex workflow - get's a bit visually unclear due to the loops etc.
<img width="970" alt="More-complex-workflow" src="https://user-images.githubusercontent.com/4522947/162396983-c09b07f0-a378-4710-a479-ddb80bdcc8f3.png">

**Comment by Kholid060** [comment]
To support all those features it may need to build the editor from scratch because [Drawflow](https://github.com/jerosoler/Drawflow/) which library for build flow doesn't have that kind of API.

**Comment by fosple** [comment]
I guess that's indeed way too much work. From my point of view the current implementation with Drawflow already does the job quite well. Maybe it's then more about improving Drawflow here and there. 

Mainly:
- Select and move multiple blocks
- Make connections between blocks behave less like "Spagetti", but more like in bpmn.io with straight lines and edges.
- Copy&paste blocks 

Will make some suggestions to the Drawflow project then. Thanks for the fast reply.
