### ISSUE TITLE
slidebar move

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#436]
Targeturl:https://www.wjx.cn/vj/my3QCgK.aspx
how can i move to value of 100, need your help

**Comment by Kholid060** [comment]
Try this workflow, don't put your mouse on the webpage when you run the workflow.

[mouse.txt](https://github.com/Kholid060/automa/files/8455988/mouse.txt)

**Comment by whwh656** [comment]
Thanks,it works, I want to ask a question.
os:macos
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/20383505/162553957-a80fc99d-d4be-4334-b2df-45c7468e460f.png">
clientX :1000,  I don't know why choose 1000. We change the number 1000 to 500 is the same effect

**Comment by Kholid060** [comment]
the `clientX` is to tell Automa to move the mouse horizontally in pixels, I put 1000 because I don't know how many pixels that's needed to move the slider until it is 100%
