### ISSUE TITLE
The new "On error occurs" feature always causes error in javascript code block

### ISSUE THREAD

**Issue by stee-ift** [Kholid060/automa#443]
**Describe the bug**
The new "On error occurs" feature always causes error in javascript code block

**To Reproduce**
1. Create a new workflow, add a javascript code block
2. execute the workflow
3. You can see the error from log: "Cannot read properties of undefined(reading '$error')"
4. The "On error occurs" doesn't need to be enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/90451454/163106231-3cf7c40a-ce4e-4ec6-a5ce-9bd3a3e49f32.png)

![image](https://user-images.githubusercontent.com/90451454/163106547-ec50974b-1936-45ef-bd54-fe1555252cdf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Google Chrome v100.0.4896.75
 - Extension Version: v1.7.1

**Comment by Kholid060** [comment]
Fixed in v1.7.2

**Comment by jddcef** [comment]
Cannot read properties of undefined (reading 'data')

I'm getting this now if I use a switch tab block before the javascript block.  If I use the "Execute every new tab" on the javscript block.

Using a new New Tab block works better than the Switch Tab block above.
But with a New Tab block placed before the javascript Code block, then it doesn't give that error, but it then doesn't even execute the javascript block if I put ""Execute every new tab"" on the javascript block (silently passes/silent fail).
