### ISSUE TITLE
Cannot read properties of undefined (reading $error)

### ISSUE THREAD

**Issue by edwyn-amador** [Kholid060/automa#446]
Please fix the following error:
![image](https://user-images.githubusercontent.com/36249854/163214214-2ba151d0-128e-4035-8011-fe1f30127d33.png)

This happens even when everything works perfect on the JavaScript module and cancels continue the workflow...

I'm just printing on console, all this happened when I realized Automa broke the syntax:

automaRefData("dataColumns", "0.key")

Now I changed it to: automaRefData("table", "0.key")

And it is printed correctly on console but still throwing that "Cannot read properties of undefined (reading $error)" error and cancelling the workflow, please fix it.

**Comment by Kholid060** [comment]
Which version are you using?

**Comment by edwyn-amador** [comment]
It just updated to 1.7.2 and it is working now, thanks :)

[Edwyn Amador - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1iac61)	[1iac61]

On April 14, 2022 at 0:42 GMT, Ahmad Kholid ***@***.***> wrote:

Which version are you using?
