### ISSUE TITLE
Loop Breakpoint: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by haikbvn** [Kholid060/automa#450]
**Describe the bug**

```
Loop Breakpoint
Cannot read properties of undefined (reading 'type')
```

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="727" alt="Screen Shot 2022-04-18 at 22 29 26" src="https://user-images.githubusercontent.com/1848623/163832710-00801dde-c2b6-44fe-9b64-16d34ac82fe5.png">
<img width="1006" alt="Screen Shot 2022-04-18 at 22 29 52" src="https://user-images.githubusercontent.com/1848623/163832724-c7c8f3de-1d59-44be-881b-ab88bc437d3d.png">

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: Google Chrome
 - Extension Version: v1.7.2

**Additional context**

**Comment by jddcef** [comment]
I'm getting this issue now: `Cannot read properties of undefined (reading 'type')`
on a loop breakpoint block.  :(

**Comment by jddcef** [comment]
> I'm getting this issue now: `Cannot read properties of undefined (reading 'type')` on a loop breakpoint block. :(
It happened because the loop block wasn't included in the loop going back...
Perhaps the message could specifiy something about that
