### ISSUE TITLE
Which path automa loads workflow from ?

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#452]
I want to know automa how to loads workflow scripts , and where  are they saved in my own computer?

which path does  automa  choose to load the file?

<img width="511" alt="image" src="https://user-images.githubusercontent.com/20383505/164012594-4a6dd183-906a-4854-ab63-4f1eb8bac72b.png">

**Comment by Kholid060** [comment]
Automa doesn't load the workflows from a file. The workflows are stored using the [`chrome.storage`](https://developer.chrome.com/docs/extensions/reference/storage/) API, you can see all of it by opening the Automa dashboard, open the dev tools (`ctrls+shift+i`), and in the console tab write:

```js
chrome.storage.local.get('workflows', ({ workflows }) => {
  console.log(workflows)
});
```
![image](https://user-images.githubusercontent.com/22908993/164108943-7e8f626f-f0b0-468e-92f7-1fd69d4294c5.png)

**Comment by whwh656** [comment]
Thanks
