### ISSUE TITLE
Save Asset block => filename = `{{ variables@filename.0 }}` not working to add custom names to images

### ISSUE THREAD

**Issue by cannibalox** [Kholid060/automa#457]
## **Describe the bug**

when I use the block `Save assets` with `filename = {{ variables@filename.0 }}` : the variable looks correct but the saved file is named  with its original name (4605509_627991789_46947422.jpg) instead of using the `{{ variables@filename.0 }}` variable that is passed from a  js block.
(in this example, `{{ variables@filename.0}} = The+Matrix+%21%21+On+VHS%21+and+DVD+%21+%21+on+Twitter%3A+%22Painting+i+did+as+a+background+for+an+animation+https%3A%2F%2Ft.co%2FGsYlpQ2eib%22+%2F+Twitter.jpg` as seen in the screenshots)

- the workflow
  ![image](https://user-images.githubusercontent.com/4605693/164349968-2c8b51f2-bb86-4833-889a-70830a583f6f.png)

- the javascript snippet to fetch and transform ata to get the correct filename and pass it as {{ variables@filename.0 }} :  
  ```js
  console.log('<<<<<<<<<<<<< fetch image name >>>>>>>>>>>>>')
  const imagesource = automaRefData('variables', 'imgsrc');
  //get image name
  const filename = imagesource.toString().split('/').pop().split('?image',1);
  console.log('image name: ', filename);
  
  automaSetVariable('filename', filename);
  automaNextBlock();
  ```
- the console.log output the correct filename, as confirmed by the workflow log, but the saved image doesn't inherit the correct filename (top right):
  ![unknown](https://user-images.githubusercontent.com/4605693/164349653-94fa9dad-6091-4f21-85a9-14649af4bbf6.png)

- the save assets block
  ![unknown](https://user-images.githubusercontent.com/4605693/164349682-3cd97105-4dbf-4a78-aca9-f88a64f3ddc4.png)

## **To Reproduce**
try to pass a variable to the `Save Assets>filename` option 

## **Expected behavior**
the saved asset should e renamed according to the value of the variable

## **Desktop (please complete the following information):**
 - Windows
 - Browser: Chrome
 - Extension Version: v1.7.2 and v1.8.0

**Comment by Kholid060** [comment]
I don't actually know what's going wrong because when I try to reproduce it everything is working as intended.

**Comment by cannibalox** [comment]
actually the `filename` option doesn't work at all for me, even if I input a sting like `testimage` or `testimage.jpg`.
here's a basic test workflow that failed to rename images :(it saves all `img` with filename `testimage` and uniquify on)
```
{"extVersion":"1.8.0","name":"save assets","icon":"riGlobalLine","table":[],"version":"1.8.0","drawflow":"{\"drawflow\":{\"Home\":{\"data\":{\"da2f21d4-43c6-4eac-80fc-4396be12912e\":{\"id\":\"da2f21d4-43c6-4eac-80fc-4396be12912e\",\"name\":\"trigger\",\"data\":{\"description\":\"\",\"type\":\"manual\",\"interval\":60,\"delay\":5,\"date\":\"\",\"time\":\"00:00\",\"url\":\"\",\"shortcut\":\"\",\"activeInInput\":false,\"isUrlRegex\":false,\"days\":[]},\"class\":\"trigger\",\"html\":\"BlockBasic\",\"typenode\":\"vue\",\"inputs\":{},\"outputs\":{\"output_1\":{\"connections\":[{\"node\":\"bc7d6e50-a6d0-47b9-9eff-324570f19949\",\"output\":\"input_1\"}]}},\"pos_x\":-215,\"pos_y\":236},\"be347b2d-f781-4ca0-854f-49b5837394ae\":{\"id\":\"be347b2d-f781-4ca0-854f-49b5837394ae\",\"name\":\"save-assets\",\"data\":{\"description\":\"\",\"findBy\":\"cssSelector\",\"waitForSelector\":false,\"waitSelectorTimeout\":5000,\"selector\":\"img\",\"markEl\":false,\"multiple\":true,\"type\":\"element\",\"url\":\"\",\"filename\":\"testimage\",\"onConflict\":\"uniquify\",\"onError\":{\"retry\":false,\"enable\":true,\"retryTimes\":1,\"retryInterval\":2,\"toDo\":\"error\"}},\"class\":\"save-assets\",\"html\":\"BlockBasic\",\"typenode\":\"vue\",\"inputs\":{\"input_1\":{\"connections\":[{\"node\":\"ec8ffd73-9a36-443a-a65e-de0b556801ed\",\"input\":\"output_1\"}]}},\"outputs\":{\"output_1\":{\"connections\":[]}},\"pos_x\":454,\"pos_y\":246},\"ec8ffd73-9a36-443a-a65e-de0b556801ed\":{\"id\":\"ec8ffd73-9a36-443a-a65e-de0b556801ed\",\"name\":\"element-exists\",\"data\":{\"findBy\":\"cssSelector\",\"selector\":\"img\",\"tryCount\":1,\"timeout\":500,\"markEl\":false,\"throwError\":false},\"class\":\"element-exists\",\"html\":\"BlockElementExists\",\"typenode\":\"vue\",\"inputs\":{\"input_1\":{\"connections\":[{\"node\":\"bc7d6e50-a6d0-47b9-9eff-324570f19949\",\"input\":\"output_1\"}]}},\"outputs\":{\"output_1\":{\"connections\":[{\"node\":\"be347b2d-f781-4ca0-854f-49b5837394ae\",\"output\":\"input_1\"}]},\"output_2\":{\"connections\":[]}},\"pos_x\":220,\"pos_y\":202},\"bc7d6e50-a6d0-47b9-9eff-324570f19949\":{\"id\":\"bc7d6e50-a6d0-47b9-9eff-324570f19949\",\"name\":\"active-tab\",\"data\":{},\"class\":\"active-tab\",\"html\":\"BlockBasic\",\"typenode\":\"vue\",\"inputs\":{\"input_1\":{\"connections\":[{\"node\":\"da2f21d4-43c6-4eac-80fc-4396be12912e\",\"input\":\"output_1\"}]}},\"outputs\":{\"output_1\":{\"connections\":[{\"node\":\"ec8ffd73-9a36-443a-a65e-de0b556801ed\",\"output\":\"input_1\"}]}},\"pos_x\":-7,\"pos_y\":234}}}}}","settings":{"restartTimes":3,"inputAutocomplete":true,"blockDelay":0,"saveLog":true,"debugMode":true,"reuseLastState":false,"onError":"stop-workflow","executedBlockOnWeb":false},"globalData":"[{ \"key\": \"value\" }]","description":"","includedWorkflows":{}}
```

I must be missing something obvious. using win 10 chrome 100

**Comment by cannibalox** [comment]
found the issue : had dextensions that prevented the block from functionning properly (image downloader and chrono download manager). The `save assets` block works fine once the extensions are disabled.

sorry for the trouble and thank you for checking !
