### ISSUE TITLE
js notifications

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#460]
https://developer.mozilla.org/zh-CN/docs/Web/API/notification

automa support  js notifications ?

**Comment by Kholid060** [comment]
Automa doesn't support notification, but you can show js notification by using the javascript code block.

**Comment by whwh656** [comment]
> Automa doesn't support notification, but you can show js notification by using the javascript code block.

chrome:100
os:macos
automa:1.8.0
it doesn't have effect in js block i have open chorme permissions


let permission = Notification.permission;
if(permission === "granted") {
   showNotification();
} else if(permission === "default"){
   requestAndShowPermission();
} else {
  alert("Use normal alert");
}
function showNotification() {
   if(document.visibilityState === "visible) {
       return;
   }
   var title = "JavaScript Jeep";
   icon = "https://app.modaiyun.com/damf/download-asset/ccddd.jpg/8559163"
   var body = "Message to be displayed";
   var notification = new Notification('Title', { body, icon });
   notification.onclick = () => { 
          notification.close();
          window.parent.focus();
   }
}
function requestAndShowPermission() {
   Notification.requestPermission(function (permission) {
      if (permission === "granted") {
            showNotification();
      }
   });
}
automaNextBlock()

**Comment by Kholid060** [comment]
Try this script
```js
function notifyMe(message, options = {}) {
  if (Notification.permission === 'granted') {
    const notification = new Notification(message, options);
    notification.onclick = () => {
      notification.close();
      window.parent.focus();
    };
  } else if (Notification.permission === 'default') {
    Notification.requestPermission().then((permission) => {
      if (permission === 'granted') {
        notifyMe(message, options);
      }
    });
  } else {
    alert(message);
  }
}

notifyMe('JavaScript Notification', {
  icon: 'https://app.modaiyun.com/damf/download-asset/ccddd.jpg/8559163',
  body: 'Message to be displayed'
});

automaNextBlock()
```

If it still does not work, try to check your OS settings. Make sure you allow chrome to show a notification, for example in windows

![image](https://user-images.githubusercontent.com/22908993/164965515-e5f46e60-858d-44ef-b983-9ea1ad94c848.png)

**Comment by whwh656** [comment]
thanks
