### ISSUE TITLE
请问，项目克隆下来npm run dev 启动成功后，怎么能看到页面

### ISSUE THREAD

**Issue by xtt-lydia** [Kholid060/automa#464]
**Describe the bug**
请问，项目克隆下来npm run dev 启动成功后，怎么能看到页面，具体在哪开发调试
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser: [e.g. Google Chrome]
 - Extension Version: [e.g. v0.12.0]

**Additional context**

**Comment by Kholid060** [comment]
1. Open the `chrome://extensions` page
2. Enable the `Developer mode` on the top right
3. Drag and drop the `build` folder in your Automa project

**Comment by xtt-lydia** [comment]
Thanks,After I put the project npm run dev in the extension program successfully, the error is as follows：
![Snipaste_2022-04-28_10-04-36](https://user-images.githubusercontent.com/45763695/165661842-1fa15c85-29ab-4a30-aaad-dd7916e24a1e.png)

**Comment by Kholid060** [comment]
Can you translate the error message to English?

**Comment by xtt-lydia** [comment]
Failed to load extension successfully document
D:\work\soft\automa-main
mistake
file or not readable
Failed to load manifest.

**Comment by xtt-lydia** [comment]
thanks  a lot, 已解决，原来是把打包好后的生成文件夹放进去
