### ISSUE TITLE
"Save as" window showing up late when extension is enabled

### ISSUE THREAD

**Issue by Fabian9799** [Kholid060/automa#465]
**Describe the bug**
The "save as" dialog shows up after up to 20 seconds after i try to download anything when the extension is enabled (with all workflows disabled)

**To Reproduce**
1. Install Automa
2. Download any file / image

**Expected behavior**
The file should download instantly

**Actual behaviour**
It takes up to 20 seconds until a file downloads
https://www.youtube.com/watch?v=p6r0TwR-Oyg

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 21H2 (Build 22000.613)
 - Browser: 1.37.116 Chromium: 100.0.4896.127 (Brave)
 - Extension Version: 1.9.1

**Comment by Kholid060** [comment]
This might happened when granted Automa the download permissions, I'll try to fix it.
