### ISSUE TITLE
ERROR when run 'yarn dev'

### ISSUE THREAD

**Issue by franklinzk53** [Kholid060/automa#466]
run script 'yarn dev' 
Can't resolve './get-pass-key' in 'D:\WorkSpace\automa\src\utils' please see the picture bellow:

![image](https://user-images.githubusercontent.com/34902517/165543455-d8d22695-3313-4495-970e-91ce8fadf249.png)

**Comment by Kholid060** [comment]
See https://github.com/Kholid060/automa/issues/301

**Comment by franklinzk53** [comment]
thanks for your replay
