### ISSUE TITLE
我在google上不能使用这个元素选择功能。

### ISSUE THREAD

**Issue by shuaishuai1999** [Kholid060/automa#47]
https://user-images.githubusercontent.com/52946262/141034042-9952c7e2-901b-437b-961f-4ebf34b4b9ae.mp4

**Comment by shuaishuai1999** [comment]
my Chrome version is 版本 95.0.4638.69（正式版本） （64 位）

**Comment by Kholid060** [comment]
Element selector only working when you're on a website, if it's a new tab or the URL starts with `chrome://` it won't work.

**Comment by shuaishuai1999** [comment]
ok. thk u
