### ISSUE TITLE
handle dialog block no effect

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#473]
[alert.html.txt](https://github.com/Kholid060/automa/files/8595457/alert.html.txt)
automa:1.9.3
chrome
macos
I have open debug mode but it doesn't work

1  I use a  localocal server to display the static test  file :alert.html:
you may need to change the alert.html.txt to alert.html
2
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/20383505/166085450-4468f025-79b9-487b-9792-f5eaa992a47e.png">

3 I want to input txt  and click sure button
[testalert.txt](https://github.com/Kholid060/automa/files/8595444/testalert.txt)

**Comment by Kholid060** [comment]
I think there's a bug in the app, I'll try to fix it

**Comment by whwh656** [comment]
Thanks

**Comment by Kholid060** [comment]
Fixed in v1.9.4, but one thing you need to know is that when using the `Handle dialog` block, you need to connect it before the dialog occurs.
![image](https://user-images.githubusercontent.com/22908993/166106166-fc6f3872-2f72-433d-beb8-d38833919fb2.png)
