### ISSUE TITLE
take screenshot  by element

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#475]
targeturl: https://www.google.com.hk/
take screen google's logo
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/20383505/166395346-485216a4-8280-4ce0-baba-1918530c4581.png">

but the screenshot is blank picture
<img width="515" alt="image" src="https://user-images.githubusercontent.com/20383505/166395407-63dfda22-4b3c-4da7-bf81-4221daa5687b.png">

**Comment by Kholid060** [comment]
I don't know what's going wrong because it working when I tested it

![screenshot-element](https://user-images.githubusercontent.com/22908993/166616346-315ffb21-eb21-474e-9186-68376ced7b0d.gif)

**Comment by whwh656** [comment]
os:macos
chrome:101
automa:1.9.4
