### ISSUE TITLE
Flow Marketplace

### ISSUE THREAD

**Issue by hudsonbrendon** [Kholid060/automa#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
You could create a "store" with general purpose flows created and shared by users, you could search from a repository and list/categorize it on the main screen.

**Describe alternatives you've considered**

**Additional context**

**Comment by Kholid060** [comment]
I actually have a plan to do this, but I want to make the documentation for the extension first and then build the marketplace.
