### ISSUE TITLE
How to click a element list dom one by one for some time delay cyclily?

### ISSUE THREAD

**Issue by Arethusa2012** [Kholid060/automa#490]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kholid060** [comment]
You can loop the elements first using the [loop data block](https://docs.automa.site/blocks/loop-data.html#loop-data-block) and inside the loop add the click element block and the delay block.

![image](https://user-images.githubusercontent.com/22908993/167795129-f84c7627-38c3-4d77-9cf1-60ce1d823ab4.png)

Import the below workflow into Automa as a demo, but you need to change the file extension from `txt` to `json`
[loop-elements.txt](https://github.com/Kholid060/automa/files/8667720/loop-elements.txt)

**Comment by Arethusa2012** [comment]
> You can loop the elements first using the [loop data block](https://docs.automa.site/blocks/loop-data.html#loop-data-block) and inside the loop add the click element block and the delay block.
> 
> ![image](https://user-images.githubusercontent.com/22908993/167795129-f84c7627-38c3-4d77-9cf1-60ce1d823ab4.png)
> 
> Import the below workflow into Automa as a demo, but you need to change the file extension from `txt` to `json` [loop-elements.txt](https://github.com/Kholid060/automa/files/8667720/loop-elements.txt)

Thanks, I will try it.

**Comment by Arethusa2012** [comment]
This works, thanks.
