### ISSUE TITLE
Does this extension support to run at the target time like 8:30:00 every day?

### ISSUE THREAD

**Issue by lynnk1ng37** [Kholid060/automa#53]
**Is your feature request related to a problem? Please describe.**
1. I want to know does this extension support to run at the target time, like 8:30:00 means it will run at 8:30:00 every day?
2. And if I don't close Chrome Browser but lock my computer, will it run?

**Describe the solution you'd like**
I hope it supports to run at the target time.

**Describe alternatives you've considered**
As I know, we can get current system time and use an if to do this.
    var currentHours= new Date().getHours();
    var currentMin= new Date().getMinutes();
    var currentSec= new Date().getSeconds();
    if(currentHours=='8' && currentMin=='30' && currentSec=='00'){
        // execute this task
    }

**Additional context**

**Comment by Kholid060** [comment]
Duplicate #35
