### ISSUE TITLE
How to create a workflow to close tabs that have a certain element in them?

### ISSUE THREAD

**Issue by jashshah** [Kholid060/automa#59]
Hello, 

Fantastic idea on creating a chrome extension to automate workflows.

In absence of documentation can you help me/point me in the direction to execute the following:

for all tabs that are open in chrome:
1. find all that match a URL pattern
2. If the webpages contains a certain element then close it.

**Comment by Kholid060** [comment]
You can close all tabs that match the URL pattern by unchecking the "Close active tab" when you edit the close tab block, but it's not possible to close tabs that have certain elements in it
