### ISSUE TITLE
unable to execute js from javascript block

### ISSUE THREAD

**Issue by bawatrader** [Kholid060/automa#63]
**Describe the bug**
Trying to execute button click through javascript code but unable to do so

**To Reproduce**
Pls find snap
![image](https://user-images.githubusercontent.com/74675840/141174897-1deebcd2-b92c-4cbb-a484-5e0cfa70248d.png)

**Expected behavior**
If I execute js snippet from the dev tools console tab then it is able to click on button but i m not able to get it done from javascript block.

**Screenshots**

**Additional context**
If we can get any guidance on how to execute custom javascript then that would help

**Comment by bawatrader** [comment]
![image](https://user-images.githubusercontent.com/74675840/141229214-36d70337-ceb8-49c3-a3b6-8156eefd152a.png)
this is the log snap...log also do not show js being executed

**Comment by Kholid060** [comment]
If you see a script element with `automa-custom-js` ID on the website that you want to execute js in, that means it's working. And try to see the console tab if there's an error or not

**Comment by bawatrader** [comment]
thanks for your reply @Kholid060 

yes...i can see script in the website

![image](https://user-images.githubusercontent.com/74675840/141234788-1c9139c7-b0c8-44c2-8908-f1575a498d5e.png)

but log window do not show js block getting executed and can you pls help me to figure out "how can i ensure that it getting triggered?"

**Comment by Kholid060** [comment]
Try console.log the `document.getElementsByClassName` to check if the element exist or not.

**Comment by bawatrader** [comment]
it does exists.

pls find snap 

![image](https://user-images.githubusercontent.com/74675840/141339002-0b653ead-8656-43c3-9d72-64ae20988867.png)

If i execute the code manually on console then the click also works.

this is automa log

![image](https://user-images.githubusercontent.com/74675840/141339133-9e179b3b-c10c-4320-81e7-c010e263b0a3.png)

**Comment by bawatrader** [comment]
With a few more debugging, identified that code is getting executed but a single statement gets executed four times, it might be causing button to be activate->de-activate->activate->de-activate

![image](https://user-images.githubusercontent.com/74675840/141341920-90fd9ee3-d858-4af4-b6c4-5c65f703b2e9.png)

this is code snippet

![image](https://user-images.githubusercontent.com/74675840/141341982-edd54ee2-494a-463d-90d5-f7d7d55da4ce.png)

Question is, why single statement gets executed four times?

**Comment by Kholid060** [comment]
I don't why this happened, because javascript only executed once on the website that I've tested so far. But I'll try to fix it

**Comment by bawatrader** [comment]
thank you

I am also trying to figure out, will update my finding over here.
