### ISSUE TITLE
How to select one item in selectbox? 

### ISSUE THREAD

**Issue by Arethusa2012** [Kholid060/automa#64]
**Describe the bug**
How to select one item in selectbox? I have tried many times, but it doesn't work.
Can you give some examples about select usage?

**Comment by Kholid060** [comment]
For the select usage, you need to input the selector of the select element and then input the option value (see image) that you want to select in value input at the forms block. 
For example, if you want to select the `Created date`, you only need to write `createdAt` at forms block value input. You can see the option value by opening the devtool (ctrl+shift+c) and then hover the mouse into the select element.

![image](https://user-images.githubusercontent.com/22908993/141435298-0090f3c6-c332-4e7d-ac40-548b06349c26.png)

**Comment by Arethusa2012** [comment]
> For the select usage, you need to input the selector of the select element and then input the option value (see image) that you want to select in value input at the forms block. For example, if you want to select the `Created date`, you only need to write `createdAt` at forms block value input. You can see the option value by opening the devtool (ctrl+shift+c) and then hover the mouse into the select element.
> 
> ![image](https://user-images.githubusercontent.com/22908993/141435298-0090f3c6-c332-4e7d-ac40-548b06349c26.png)

Tks, I get it.
