### ISSUE TITLE
I trigger a time on 8:50, but it runs at 8:00

### ISSUE THREAD

**Issue by lynnk1ng37** [Kholid060/automa#66]
**Describe the bug**
Hi, I triggered a specific time on 8:50, but it runs at 8:00, did this setting time only match hour for run?
![image](https://user-images.githubusercontent.com/60334442/141392521-dc25eecc-37db-42bd-9e7e-63b184304765.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bxb100** [comment]
It's a bug
the code just using `new Date("2021-11-12")` that result is UTC time, so the epoch timestamp is `1636675200000`,  that you brower fire on the `8:00` just because +8 timezone
