### ISSUE TITLE
Go through a list of links

### ISSUE THREAD

**Issue by Chokeey** [Kholid060/automa#71]
Hello,
I wanted you to add a custom block that allows the user to input a list of links, it's like the "New Tab" block but in bulk.

Trigger > New Tab > Click Element > Delay > (I want a block that I can input a list of links and it would loop the workflows normal and when it would reach this said block, it would open a link from the list and repeat the workflow). 

A collection of the links might look something like this:

(https://github.com/1)
(https://github.com/2)
(https://github.com/3)
(https://github.com/4)
(https://github.com/5)
(https://github.com/6)
(https://github.com/7)
(https://github.com/8)
(https://github.com/9)
(https://github.com/10)

I saw the new loop block though I don't know if that allows me to do what I want. If this is already possible could you please explain to me how I would go about this? I plan to a list of over 10,000 links, so putting the 'New Tab' block is not an option.

Maybe you can implement this option to the 'New tab' block, so the user would input a list of links and every time the workflow would reach the 'New tab' block it would go down the list of links inputted. It would look something like this.

Trigger > **New tab** > Click element > Loop

The 'New tab' block, in this case, would have a list of links and every time the workflow is looped it would go through the list. 
Thanks

**Comment by Kholid060** [comment]
You can use the [Loop data block](https://github.com/Kholid060/automa/wiki/Blocks#loop-data) to do this task. Make a workflow that looks like this

Trigger > Loop data block > New tab > Click element > Loop breakpoint block

1. At the Loop data block click edit, at the selection select "Custom data", click insert, and insert your list of links like this
`
["https://github.com/1", "https://github.com/2", ...]
`
or import your CSV file if you have one.
2.  At the URL input new tab block write `{{ loopData@loopID }}`, you can find the `loopID` when you edit the Loop data block.
3. And in the [Loop breakpoint block](https://github.com/Kholid060/automa/wiki/Blocks#loop-breakpoint) input the `Loop ID.
4. Execute it, and when it reaches the Loop breakpoint. It will start from the new tab until the last link.

Note: if you see a hyphen (-) or underscore (_) symbol in the Loop ID when you edit the Loop data block, make sure you delete it.

**Comment by Kholid060** [comment]
The extension doesn't have access to a URL that starts with `chrome-extension://` or `chrome://`
