### ISSUE TITLE
Dynamic URL parameters broken

### ISSUE THREAD

**Issue by marcwiest** [Kholid060/automa#73]
**Describe the bug**
The last update broke the text replacing for "New Tab" URL #11 , even with new syntax (ie. `{{}}` instead of `[]`) applied.

**To Reproduce**
1. Implement "New Tab" action
2. Try the text replacement inside the URL

**Expected behavior**
The dataColumns strings should be replaced before the new tab is opened, but they aren't.

**Desktop (please complete the following information):**
 - OS: OSX 11.5.2
 - Automa: 0.4.1
 - Chrome: 95.0.4638.69

**Comment by marcwiest** [comment]
<img width="177" alt="Screen Shot 2021-11-12 at 11 58 23 AM" src="https://user-images.githubusercontent.com/815624/141463705-c22b237c-0aa2-4ab6-870e-72950a40ef7b.png">

**Comment by Kholid060** [comment]
Is there's any symbol beside the dot and at (@) inside the curly brackets?

**Comment by Kholid060** [comment]
Both `dataColumn` and `dataColumns` will work.

**Comment by marcwiest** [comment]
> Is there's any symbol beside the dot and at (@) inside the curly brackets?

I'm using 2 dataColumn entries. They look like this: `{{ dataColumns@some-key }}-{{ dataColumns@other-key }}`.

**Comment by Kholid060** [comment]
Update the extension to v0.4.4, it should be working now

**Comment by marcwiest** [comment]
Just update, but it's still not working.

**Comment by Kholid060** [comment]
I think this is not working because the regex fails when there are multiple references inside the string. But I have fixed it and it's in the review process,

**Comment by marcwiest** [comment]
Yep. It's working for me now. Thanks
