### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by SvenVH2** [Kholid060/automa#75]
First of all I want to say Thank you for adding this feature so fast!
But I'm having some trouble with it. If I put this in my custom loop data
`[
  { name: 'foo bar', age: 20 },
  { name: 'bar foo', age: 21 },
]`

I receive this error:
"Unexpected token n in JSON at position 6"

What am I doing wrong?

**Comment by Kholid060** [comment]
Sorry, I forget the input only accepted JSON. So you need to convert the data above like these
```json
[{ "name": "foo bar", "age": 20 }, { "name": "bar foo", "age": 21 }]
```
