### ISSUE TITLE
Element selector select multiple elements

### ISSUE THREAD

**Issue by DaiZack** [Kholid060/automa#77]
in the Element selector, it can only select one element at a time. 

![1](https://user-images.githubusercontent.com/45176371/141602023-e5b5fd3a-8af8-4f4c-8d45-1b8057137d81.png)

It would be nice if can generate multi-element selectors.
Like 

![2](https://user-images.githubusercontent.com/45176371/141602055-41805ebe-fff8-4230-83de-66dc695d1a76.png)

**Comment by Kholid060** [comment]
This is because [@medv/find](https://github.com/antonmedv/finder) library that I use to generate the CSS selector doesn't support a multi-element selector, but I'll try to resolve this issue
