### ISSUE TITLE
Repeat operation

### ISSUE THREAD

**Issue by DaiZack** [Kholid060/automa#78]
When edit the workflow it is not easy to repeat same operation. like get data->next page -> get data-> next page ->...
one of those feature would make things easier:
  1. enable duplicate node.
  2. create loop processes function.
  3. change the exported json "drawflow" type from string to object, so we can easily edit it in json editors.

**Comment by Kholid060** [comment]
1. Definitely a useful feature, will add it.
2. If you want to loop through data you can use the **Loop data block**, or if you doing a repetitive task as you mentioned you can use the **Repeat task block** like the image below
![image](https://user-images.githubusercontent.com/22908993/141604886-3157051f-f2fd-452f-8295-8ede9745806d.png)
3. I'm not gonna change the "drawflow" into an object, if you want to edit it in a JSON editor you can convert it temporarily into an object
