### ISSUE TITLE
The page zoom causes the connection line to be misaligned

### ISSUE THREAD

**Issue by codedog00** [Kholid060/automa#79]
**Describe the bug**
The page zoom causes the connection line to be misaligned

**To Reproduce**
Zoom the entire page

**Screenshots**
![20211113143649](https://user-images.githubusercontent.com/91818354/141609329-6f8deee3-f242-4031-9563-dddedd74ab01.png)

![20211113143722](https://user-images.githubusercontent.com/91818354/141609336-661e071d-74f7-4e63-8404-70dfba04e75f.png)

**Laptop (please complete the following information):**
 - OS: windows 10 21H1
 - Version 0.4.5
 - Microsoft Edge： 95.0.1020.44

**Additional context**
My windows display settings are set to zoom in 125%，so without zooming, it looks misplaced.

**Comment by Kholid060** [comment]
The fix is on the way
