### ISSUE TITLE
launch automatically when opening chrome

### ISSUE THREAD

**Issue by bomayso** [Kholid060/automa#83]
can you make it launch automatically when chrome is opened?
i have selected "Resume from where you left off" in chrome but its not working.

**Comment by Kholid060** [comment]
> can you make it launch automatically when chrome is opened

To make the extension or the workflow that launches automatically?

**Comment by bomayso** [comment]
> > can you make it launch automatically when chrome is opened
> 
> To make the extension or the workflow that launches automatically?

i have a script, i want when i open chrome it will launch automatically.

**Comment by Kholid060** [comment]
Because Chrome doesn't have an API to listen when chrome is opened, this feature won't be added

**Comment by bomayso** [comment]
Thank you for listening!!
