### ISSUE TITLE
Interact with elements

### ISSUE THREAD

**Issue by Chokeey** [Kholid060/automa#84]
Hello,

I was wondering if it were possible for you to add an option for the user to interact with elements besides clicking it. For example, I need to interact with a form though I don't need to type numbers or letters rather I need to input a set of arrow keys. Could you make it so that a block is able to input things like the Up arrow and Down arrow keys, backspace, CRTL e.tc?

Maybe this is already possible, I'm just not too sure how to go about it.

Thanks in advance.

**Comment by Kholid060** [comment]
You can use **Trigger event block** to do this, because `input` event currently doesn't available you can use `keydown` or `keyup` . To input arrow down in a form, in the options, input `code` and `key` with `ArrowDown`.
