### ISSUE TITLE
Loop data block 

### ISSUE THREAD

**Issue by Chokeey** [Kholid060/automa#85]
When you go to import data into the 'Loop data' block it doesn't support much. I am trying to import a list of 10,000 links but it cuts it down to the first 699 links even though it doesn't cross the limit of 1MB. Please refer to the video below. 

In the video, I copy and paste the links, though I have also tried to import the list using a CSV, JSON, XLSX, though I got the same result.
I also attached a list of 10,000 links if you would like to test this out yourself.

https://user-images.githubusercontent.com/90982478/141690913-833847a8-1d3a-416d-94c0-275649f2d370.mp4

[List of 10k links.txt](https://github.com/Kholid060/automa/files/7534231/List.of.10k.links.txt)

**Comment by Kholid060** [comment]
It slices some of the data in the preview to prevent lag when you import a large document. But the actual data is still 10,000 when you try to loop it
