### ISSUE TITLE
I want to know how to pass data in first javascript block to  next javascript block

### ISSUE THREAD

**Issue by bibidu** [Kholid060/automa#86]

**Comment by Kholid060** [comment]
It's not possible to pass data from a javascript block to another javascript block right now

**Comment by bibidu** [comment]
so，is the automaNextBlock function designed for export data？

**Comment by Kholid060** [comment]
yes

**Comment by PatrickkZhao** [comment]
> yes

How to get the value from the previous Get Text block in javascript block ?

**Comment by Kholid060** [comment]
> How to get the value from the previous Get Text block in javascript block?

It's not possible right now, this feature might be available in the next update.
