### ISSUE TITLE
Forms populated with duplicated characters

### ISSUE THREAD

**Issue by Beniamin19** [Kholid060/automa#87]
**Describe the bug**
My automation is gathering data into table from 2 sources, CRM and google adress card.
The data in the table of Automa is fine as I checked in export file.
This is not consisten behaviour, this automation worked before, did not change much and this started to happen

Then the data should be put into microsoft forms, unfortunately the data gets into the form like this:
- Google inc.
- GGooooggllee  iinncc..

**To Reproduce**
1.Copy data into table
2. paste the data into form element:  .__question__:nth-child(2) .office-form-question-textbox

**Expected behavior**
Automa shuld paste/write into the form the exact data that is in the table.

**Screenshots**
How the data is paste'ed into the form:
![image](https://user-images.githubusercontent.com/48880590/141751242-a28d6e77-6744-4d25-87ca-e1f13deaf2c9.png)

Even when the automation did not get the data (there was no alement to copy if from) it is the same issue:
![image](https://user-images.githubusercontent.com/48880590/141751383-76ebb2b4-8108-484c-9f59-91c8f6260b17.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro 
 - compilation 19042.1348

**Comment by Kholid060** [comment]
I have tested it, and it seems like this bug happened when you add typing delay to the forms. For now, input 0 to the typing delay until the bug is fixed

**Comment by Beniamin19** [comment]
Unfortunately the bug still persists with input set to 0.

The thing that worked, was to clear cookies and browser memory. now the input is working well

**Comment by Beniamin19** [comment]
Even with input set to 0 the data right now is pasted twice. 
For example:
-Google
-GoogleGoogle

**Comment by Kholid060** [comment]
This bug happened because the content script is executed twice. But I've fixed it, and it will be out in the next version
