### ISSUE TITLE
Are there any plans to support the doll?

### ISSUE THREAD

**Issue by WangGuibin** [Kholid060/automa#88]
For example, several workflows can be executed in tandem or independently, similar to components. Just like the shortcut of iPhone, it has an operation to run shortcut instructions, that is, some written workflows can be directly called without repeated writing, and can the function of copying workflows be added?These are immature suggestions, big old ，Appreciate your work.keep fighting！ Best wishes.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Kholid060** [comment]
> For example, several workflows can be executed in tandem or independently

You can do this by creating a collection.

**Comment by WangGuibin** [comment]
@Kholid060 OK, thank you. I have seen it.
