### ISSUE TITLE
when Forms an Attribute value's Data column, seems not get the attribute value

### ISSUE THREAD

**Issue by lynnk1ng37** [Kholid060/automa#89]
**Describe the bug**
the forms value is wrong, pls have a look.
![image](https://user-images.githubusercontent.com/60334442/141879641-23586df7-0644-4c04-8464-cdba78309d6a.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by lynnk1ng37** [comment]
In before version, it forms right

**Comment by Kholid060** [comment]
Try replace `[data@0.answer]` to `{{ data@0.answer }}`

**Comment by lynnk1ng37** [comment]
{{ data@0.answer }} is ok, tks~
