### ISSUE TITLE
Option for custom javascript execution

### ISSUE THREAD

**Issue by WybeBosch** [Kholid060/automa#9]
**Is your feature request related to a problem? Please describe.**
Not all websites have "proper" unique css names (Where even :nth-child would be problematic), and sometimes you would need to use javascript to for example "Loop trough all \<p\> on the page, and check the textContent for "Apple" and if its "Apple" then click the button besides it. 

Custom javascript block could be used for much much more, and would be a nice addition for power users :D

**Describe the solution you'd like**
Add a block under "browser" or "Web interaction" to be able to add custom javascript that gets executed.

**Comment by LeoSeyers** [comment]
> **Is your feature request related to a problem? Please describe.** Not all websites have "proper" unique css names (Where even :nth-child would be problematic), and sometimes you would need to use javascript to for example "Loop trough all
> 
> on the page, and check the textContent for "Apple" and if its "Apple" then click the button besides it.
> 
> Custom javascript block could be used for much much more, and would be a nice addition for power users :D
> 
> **Describe the solution you'd like** Add a block under "browser" or "Web interaction" to be able to add custom javascript that gets executed.

+1000

*me wanna nuke sponsored content*

**Comment by Kholid060** [comment]
I will add a custom javascript block in the next version

**Comment by Kholid060** [comment]
`Custom javascript code` block has been added in v0.3.0 of the extension
