### ISSUE TITLE
how to  click element by content?

### ISSUE THREAD

**Issue by lishoujun** [Kholid060/automa#98]
hi  I have an element like  
`<a role="button" href="#" class="js-quickfilter-button  last " title="Displays issues which have been updated in the last day" data-filter-id="543">Recently Updated</a>`

how to click this by the content "Recently Updated"

**Comment by Kholid060** [comment]
It's not possible, because the "click block" relies on the element selector to know which element it should click. And the [selector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) is not capable to select an element by their content.
